In [5]:
import pandas as pd

# Load the training data
df = pd.read_csv('test_data.csv')

# Display the first few rows
print(df)

                  request                                            product
0     LED燈 35Wx1 嵌入式 220V                                    舞光/D-PD25D-EGR1
1     LED燈 20Wx1 吊管式 220V                                       舞光/L4140+65K
2     LED燈 20Wx1 吸頂式 220V                                       舞光/L4140+65K
3      LED燈 20Wx1 壁式 220V                                       舞光/L4140+65K
4     LED燈 15Wx1 嵌入式 220V                                  舞光/D-15DOP12DESR1
5     LED 燈 13Wx2 壁式 220V  舞光/OD-2054-S+LED-E2712W-EG 舞-E27X2 小螺旋壁燈銀框 +12W*2
6    LED 燈 50Wx1 壁投式 220V                     舞光/E-FLCS50D 舞-50W 凱薩泛光燈 5700K
7   LED 燈 100Wx1 壁投式 220V                   舞光/E-FLCS100D 舞-100W 凱薩泛光燈 5700K
8    LED 燈 20Wx2 吸頂式 220V             舞光/L4240+65K (組) 舞-4 尺 2 管 26W 工事燈 65K
9          LED燈 40Wx1 平板燈                       舞光/D-PD40DR7 舞-40W 柔光平板燈 65K
10         LED燈 20Wx1 山型燈                    舞光/LED-4143R5+DR7 舞-4尺單山型燈具+20W
11         LED燈 10Wx1 山型燈                    舞光/LED-2143R5+DR7 舞-2尺單山型燈具+10W
12        LED燈 100Wx1 天井燈                         舞光/D-HBAS100D 舞-100W 飛艦天井燈
13          LED燈 10Wx1 壁式                          舞光/OD-2272 舞-10W 月光壁燈 30K
14          LED燈 10Wx1 壁式                          舞光/OD-2272 舞-10W 月光壁燈 30K
15         LED燈 50Wx1 壁投式                     舞光/OD-FLZ50DR1 舞-50W 宙斯泛光燈 65K
16         LED燈 10Wx1 嵌入式              舞光/DL-51040-LO+10W 舞-E27 15" 橫崁+玻+10W
17         LED燈 10Wx1 吸頂式            舞光/EC-806+D-E2710WR10 舞-白筒燈 17X19CM+10W
18          LED燈 9Wx1 照樹燈                      舞光/OD-3174R1 舞-9W 照樹燈 30K 35°
19         LED燈 10Wx1 草皮燈                  舞光/OD-3168R2 舞-10W 馬克草皮燈 80CM 30K
20          LED燈 25Wx1 高燈             舞光/OD-1034R1+D-E2725WR3 舞-E27X1 高燈+25W

In [ ]:
import pandas as pd
import os
import fitz
from tqdm import tqdm

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_community.vectorstores import Chroma
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

# ==========================================
# 1. Document Processing & Vector DB Setup
# ==========================================
api_key = os.environ.get("OPENAI_API_KEY")

# Load PDF
doc = fitz.open("2025舞光LED21st(單頁水印可搜尋).pdf")
text = "".join([page.get_text() for page in doc])

# Chunking
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=100)
chunks = text_splitter.split_text(text)

# Embedding Model
embeddings = OpenAIEmbeddings(model="text-embedding-3-large", openai_api_key=api_key)

# Vector DB configuration
persist_dir = "./test_openai_embedding_vector_db"

if os.path.exists(persist_dir):
    import shutil
    shutil.rmtree(persist_dir)
    print("已刪除舊的向量庫，準備以 OpenAI 模型重建")

vector_db = Chroma.from_texts(
    chunks, 
    embeddings, 
    persist_directory=persist_dir
)
print(f"成功！已使用 OpenAI 嵌入模型建立資料庫。總共切分了 {len(chunks)} 個區塊。")

# ==========================================
# 2. Build the Main RAG Chain
# ==========================================
retriever = vector_db.as_retriever(search_kwargs={"k": 5})

# Primary answering model
llm = ChatOpenAI(model_name="gpt-5.2", reasoning={"effort": "medium"}, temperature=0, openai_api_key=api_key)

template = """
### 角色定位
你是一位專業的「舞光 (DanceLight)」LED 照明產品顧問。你的任務是根據提供的目錄內容，為客戶提供準確、專業且親切的產品建議。

### 檢索到的目錄內容 (Context)
{context}

### 任務指令
1. **分析需求**：判斷使用者是尋找「特定產品名稱」還是針對「特定場所」的需求並且根據使用場景來推薦產品。
2. **規格導向**：在推薦產品時，請務必從 context 中提取瓦數(W)、色溫(K)、演色性(Ra)、特殊功能。
3. **排版方式**：請使用「列點」格式，讓產品規格一目了然。

### 回答限制
- **範疇限制**：僅根據上方提供的「檢索到的目錄內容」進行回答。如果 context 中沒有相關資訊，請禮貌地回答：「抱歉，目前的產品目錄中沒有提到相關細節...」
- **嚴禁胡說**：不可自行編造產品型號、規格或價格。
- **語言一致性**：一律使用「繁體中文」回答。

---
使用者問題：{question}
顧問建議：
"""
prompt = ChatPromptTemplate.from_template(template)

qa_chain = (
    {"context": retriever, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

# ==========================================
# 3. Build the LLM Evaluator Chain
# ==========================================
# We use a fast, lightweight model specifically for binary grading
evaluator_llm = ChatOpenAI(
    model_name="gpt-4o-mini", 
    temperature=0, 
    max_tokens=5, # Keep it extremely concise
    openai_api_key=api_key
)

eval_template = """
You are a objective AI evaluator.
expected answer: {answer}

AI Response: 
{ai_answer}

Did the AI explicitly recommend or state model mentioned in the expected answer as a valid option? 
Answer with a single word: "True" or "False".
"""
eval_prompt = ChatPromptTemplate.from_template(eval_template)

# The evaluator chain
evaluator_chain = eval_prompt | evaluator_llm | StrOutputParser()

# ==========================================
# 4. Load Data & Run Evaluation Loop
# ==========================================
csv_file = "rag_training_data_merged.csv"

if not os.path.exists(csv_file):
    print(f"❌ Error: '{csv_file}' not found. Please upload it to this folder.")
else:
    df = pd.read_csv(csv_file)
    print(f"📂 Loaded {len(df)} test cases from {csv_file}")
    
    results = []
    print("\n🧪 Starting Test Run...")

    for index, row in tqdm(df.iterrows(), total=len(df)):
        user_request = str(row['question'])
        answer = str(row['answer'])
        
        try:
            # --- QUERY THE AI ---
            ai_answer = qa_chain.invoke(user_request) 
            
            # --- CHECK ACCURACY WITH EVALUATOR CHAIN ---
            # Pass the target model and the generated answer to the judge
            evaluator_decision = evaluator_chain.invoke({
                "answer": answer,
                "ai_answer": ai_answer
            })
            
            # Parse the string output into a boolean
            is_match = "true" in evaluator_decision.lower()
            
            results.append({
                "category": row['category'],
                "question": user_request,
                "answer": answer,
                "ai_answer": ai_answer,
                "match": "✅ PASS" if is_match else "❌ FAIL",
            })
            
        except Exception as e:
            results.append({
                "question": user_request,
                "answer": answer,
                "ai_answer": f"System Error: {str(e)}",
                "match": "⚠️ ERROR",
            })

    # ==========================================
    # 5. Display Results & Metrics
    # ==========================================
    result_df = pd.DataFrame(results)
    
    pass_count = len(result_df[result_df['match'] == "✅ PASS"])
    total_count = len(result_df)
    accuracy = (pass_count / total_count) * 100 if total_count > 0 else 0
    
    print("\n" + "="*40)
    print(f"📊 TEST SUMMARY")
    print("="*40)
    print(f"Total Tests: {total_count}")
    print(f"Passed:      {pass_count}")
    print(f"Failed:      {total_count - pass_count}")
    print(f"Accuracy:    {accuracy:.2f}%")
    print("="*40)

    failed_cases = result_df[result_df['match'] != "✅ PASS"]
    if not failed_cases.empty:
        print("\n❌ FAILED CASES (Preview):")
        pd.set_option('display.max_colwidth', 100)
        from IPython.display import display
        display(failed_cases[['question', 'answer', 'ai_answer', 'match']].head())
    
    output_filename = "test_results_report.csv"
    result_df.to_csv(output_filename, index=False)
    print(f"\n📝 Detailed report saved to: {output_filename}")

/Users/max/Desktop/python_codes/DanceLight--LED-AI-Chatbot-and-attribute-searching_v2/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

成功！已使用 OpenAI 嵌入模型建立資料庫。總共切分了 441 個區塊。
📂 Loaded 29 test cases from rag_training_data_merged.csv

🧪 Starting Test Run...

100%|██████████| 29/29 [07:42<00:00, 15.95s/it]

========================================
📊 TEST SUMMARY
========================================
Total Tests: 29
Passed:      4
Failed:      25
Accuracy:    13.79%
========================================

❌ FAILED CASES (Preview):

,question,answer,ai_answer,match
1,請問型號 D-FXSPL12N 的色溫、光通量及光束角分別是多少？,色溫為 4000K、光通量為 840LM、光束角為 36°。,- **需求判斷**：您是在查詢「特定產品型號 **D-FXSPL12N**」的規格（色溫 / 光通量 / 光束角）。\n\n- **目錄檢索結果**：在目前提供的目錄內容中，**D-FXSP...,❌ FAIL
3,米開朗柔性軌道系列有哪些主要特點？適合安裝在哪裡？,特點包括：軌道可彎曲以適應佈局、具備超高演色性 Ra >= 90、採低電壓安全設計。適合安裝在家中角落或商店展示空間。,- **需求判斷**\n - 你詢問的是「特定系列產品」：**舞光－米開朗柔性軌道系列**的**主要特點**與**適用安裝場所**。\n\n---\n\n## 米開朗柔性軌道系列｜主要特點（...,❌ FAIL
4,米開朗柔性軌道的燈具有什麼方便安裝的設計？,燈具設計有「按壓自動彈開扣入軌道」的功能，安裝十分便利。,- **需求判斷**\n - 你詢問的是「特定產品名稱：米開朗柔性軌道」的**燈具**安裝便利性設計（非特定場所配置）。\n\n- **米開朗柔性軌道燈具｜方便安裝的設計重點（依目錄內容）*...,❌ FAIL
5,米開朗柔性軌道投射燈的角度調整範圍是多少？,旋轉角度可達 355°，垂直調整角度可達 170°。,- **您詢問的產品**：米開朗柔性軌道投射燈 \n- **角度調整範圍（依目錄標示）**： \n - **水平旋轉**：**355°** \n - **俯仰調整**：**170°*...,❌ FAIL
7,安裝米開朗系列燈具時，電源部分有什麼需要注意的？,輸入電壓為 DC24V，且需注意驅動器為外接且費用另計。,- **先確認米開朗系列供電規格**\n - 目錄中米開朗柔性軌道系列燈具（如圓錐吊燈 D-FXPC5N / D-FXPC5W、玻璃球燈 D-FXGB6N / D-FXGB6W 等）**輸入...,❌ FAIL

📝 Detailed report saved to: test_results_report.csv

In [2]:
pd.read_csv('test_results_report.csv')

,category,question,answer,ai_answer,match,cited_pages
0,基礎規格,米開朗柔性軌道系列使用的是什麼電壓設計？,使用 DC 24V 低電壓安全通電設計。,- **需求分析**\n - 你詢問的是「特定產品系列（米開朗柔性軌道系列）」的**電壓設計規格**，屬於規格導向的查詢。\n\n- **米開朗柔性軌道系列｜電壓設計（依目錄內容）**\n ...,✅ PASS,[]
1,基礎規格,請問型號 D-FXSPL12N 的色溫、光通量及光束角分別是多少？,色溫為 4000K、光通量為 840LM、光束角為 36°。,- **需求判斷**：您是在查詢「特定產品型號 **D-FXSPL12N**」的規格（色溫 / 光通量 / 光束角）。\n\n- **目錄檢索結果**：在目前提供的目錄內容中，**D-FXSP...,❌ FAIL,[]
2,基礎規格,米開朗柔性基礎排燈的燈體材質是什麼？,材質包含鋁與 PC。,- **產品名稱**：米開朗柔性基礎排燈（基礎排燈）\n- **對應型號（目錄節錄）**：D-FXSPL12N / D-FXSPL12W \n- **燈體材質**（依目錄「燈體材質」欄位）：...,✅ PASS,[]
3,產品特性,米開朗柔性軌道系列有哪些主要特點？適合安裝在哪裡？,特點包括：軌道可彎曲以適應佈局、具備超高演色性 Ra >= 90、採低電壓安全設計。適合安裝在家中角落或商店展示空間。,- **需求判斷**\n - 你詢問的是「特定系列產品」：**舞光－米開朗柔性軌道系列**的**主要特點**與**適用安裝場所**。\n\n---\n\n## 米開朗柔性軌道系列｜主要特點（...,❌ FAIL,[]
4,產品特性,米開朗柔性軌道的燈具有什麼方便安裝的設計？,燈具設計有「按壓自動彈開扣入軌道」的功能，安裝十分便利。,- **需求判斷**\n - 你詢問的是「特定產品名稱：米開朗柔性軌道」的**燈具**安裝便利性設計（非特定場所配置）。\n\n- **米開朗柔性軌道燈具｜方便安裝的設計重點（依目錄內容）*...,❌ FAIL,[]
5,產品特性,米開朗柔性軌道投射燈的角度調整範圍是多少？,旋轉角度可達 355°，垂直調整角度可達 170°。,- **您詢問的產品**：米開朗柔性軌道投射燈 \n- **角度調整範圍（依目錄標示）**： \n - **水平旋轉**：**355°** \n - **俯仰調整**：**170°*...,❌ FAIL,[]
6,比較分析,「投射排燈」和「基礎排燈」的發光角度有什麼差別？,投射排燈的光束角為 36°，而基礎排燈的發光角度較廣，為 140°。,- **結論（發光角度差別）**\n - **投射排燈**：屬於「窄角度」集中投光，目錄中標示約 **36°**（也有頁面以光型比較標示 **40°** 的窄角概念），適合打重點、強調展示品...,✅ PASS,[]
7,規格細節,安裝米開朗系列燈具時，電源部分有什麼需要注意的？,輸入電壓為 DC24V，且需注意驅動器為外接且費用另計。,- **先確認米開朗系列供電規格**\n - 目錄中米開朗柔性軌道系列燈具（如圓錐吊燈 D-FXPC5N / D-FXPC5W、玻璃球燈 D-FXGB6N / D-FXGB6W 等）**輸入...,❌ FAIL,[]
8,規格細節,米開朗柔性軌道系列對於色彩還原度的表現如何？,表現極佳，具備 Ra >= 90 高演色性、R9 > 50 以及 SDCM < 3.5 的低色容差，確保光色無色差。,- **需求判斷（依提問內容）**\n - 你是在詢問「特定產品系列：米開朗柔性軌道系列」對於**色彩還原度（演色性）**的表現，而非特定場所配置需求。\n\n- **米開朗柔性軌道系列｜色...,✅ PASS,[]
9,產品型號查詢,請問有推薦的「LED燈 35Wx1 嵌入式 220V」產品嗎？,推薦型號為：舞光/D-PD25D-EGR1,- **需求判斷**\n - 您是在找「**特定規格**：LED燈 **35W×1、嵌入式、220V**」的產品。\n\n- **目錄比對結果**\n - 目前提供的目錄內容中，**沒有明...,❌ FAIL,[]
10,產品型號查詢,請問有推薦的「LED燈 20Wx1 吊管式 220V」產品嗎？,推薦型號為：舞光/L4140+65K,依您提出的條件「**20W×1、吊管式、220V**」，目前在這份目錄內容中**沒有完全符合（20W×1 且為吊管式）**的型號可直接對應。下面提供目錄內**最接近**的兩種方向，讓您依「吊管...,❌ FAIL,[]
11,產品型號查詢,請問有推薦的「LED燈 20Wx1 吸頂式 220V」產品嗎？,推薦型號為：舞光/L4140+65K,- **需求判斷**：您要找的是「**特定規格**（20W ×1、吸頂式、220V）」的 LED 吸頂燈。目錄中符合「可用於 220V（全電壓 100–240V）」且為 **20W 吸頂式**...,❌ FAIL,[]
12,產品型號查詢,請問有推薦的「LED燈 20Wx1 壁式 220V」產品嗎？,推薦型號為：舞光/L4140+65K,- 你的需求屬於「規格/用途導向」：想找 **壁式、單顆 20W（20Wx1）、可用 220V** 的 LED 燈具。 \n- 依目錄內容，符合 **20W 且輸入電壓涵蓋 220V（100...,❌ FAIL,[]
13,產品型號查詢,請問有推薦的「LED燈 15Wx1 嵌入式 220V」產品嗎？,推薦型號為：舞光/D-15DOP12DESR1,- **需求判斷**：您是在找「**指定規格**」的產品（**LED燈 15W×1、嵌入式、220V**）。 \n- **目錄比對結果**：抱歉，目前的產品目錄中**沒有提到**「**15W...,❌ FAIL,[]
14,產品型號查詢,請問有推薦的「LED 燈 13Wx2 壁式 220V」產品嗎？,推薦型號為：舞光/OD-2054-S+LED-E2712W-EG 舞-E27X2 小螺旋壁燈銀框 +12W*2,- **需求判斷**\n - 您的條件是「**壁式**、**LED 13W ×2**、**220V**」。\n - 目前目錄中有多款「**單顆 13W**、**100–240V(全電壓)*...,❌ FAIL,[]
15,產品型號查詢,請問有推薦的「LED 燈 50Wx1 壁投式 220V」產品嗎？,推薦型號為：舞光/E-FLCS50D 舞-50W 凱薩泛光燈 5700K,- **需求判斷**：您是要找「特定規格的產品」──**LED 壁投式 / 50W×1 / 220V**。\n\n- **目錄符合度說明**\n - 抱歉，目前的產品目錄中**沒有**明確標...,❌ FAIL,[]
16,產品型號查詢,請問有推薦的「LED 燈 100Wx1 壁投式 220V」產品嗎？,推薦型號為：舞光/E-FLCS100D 舞-100W 凱薩泛光燈 5700K,- **需求分析**\n - 您提供的是**規格/形式導向**需求：「**LED 燈 100W ×1、壁投式、220V**」，屬於想找**特定類型（壁投/投射燈）且指定瓦數與電壓**的產品。...,❌ FAIL,[]
17,產品型號查詢,請問有推薦的「LED 燈 20Wx2 吸頂式 220V」產品嗎？,推薦型號為：舞光/L4240+65K (組) 舞-4 尺 2 管 26W 工事燈 65K,- **需求判斷**\n - 你要找的是「特定規格」：**吸頂式、20W（而且要 x2 兩盞）、適用 220V** 的 LED 燈具。\n - 依目錄內容來看，最符合的是 **「20W 神...,❌ FAIL,[]
18,產品型號查詢,請問有推薦的「LED燈 40Wx1 平板燈」產品嗎？,推薦型號為：舞光/D-PD40DR7 舞-40W 柔光平板燈 65K,- **需求判斷**\n - 你是想找「**特定規格/名稱：40W、4x1 尺的 LED 平板燈**」這類型產品。\n - 但目前目錄中「**4x1 尺、40W**」可對應到的型號僅看到 ...,❌ FAIL,[]
19,產品型號查詢,請問有推薦的「LED燈 20Wx1 山型燈」產品嗎？,推薦型號為：舞光/LED-4143R5+DR7 舞-4尺單山型燈具+20W,- **需求判斷**\n - 您詢問的是**特定規格/品類**：「LED燈 20W×1 的山型燈」。\n - 不過在目前提供的目錄內容中，**沒有直接出現「山型燈」**這個品名/分類；目錄...,❌ FAIL,[]
20,產品型號查詢,請問有推薦的「LED燈 10Wx1 山型燈」產品嗎？,推薦型號為：舞光/LED-2143R5+DR7 舞-2尺單山型燈具+10W,目前目錄中**沒有直接標示「山型燈」**這個品名/系列；不過若您要找的是常見的**戶外用 10W 單顆壁燈（10Wx1）**類型，我可以先用目錄內最接近的 10W 產品提供您參考如下：\n\n...,❌ FAIL,[]
21,產品型號查詢,請問有推薦的「LED燈 100Wx1 天井燈」產品嗎？,推薦型號為：舞光/D-HBAS100D 舞-100W 飛艦天井燈,以下我判斷您是在找「100W×1 的天井燈」規格產品（非單純詢問某固定品名），目錄中目前有 **2 種 100W 等級**可對應天井/高天井空間使用，差別在於您現場是「整套天井燈具」或「E40...,❌ FAIL,[]
22,產品型號查詢,請問有推薦的「LED燈 10Wx1 壁式」產品嗎？,推薦型號為：舞光/OD-2272 舞-10W 月光壁燈 30K,- **需求判斷**：您在找的是「特定規格」— **LED 壁式燈、10W ×1（單燈）**。 \n 依目前目錄內容，符合 10W 壁燈規格的選項如下：\n\n- **推薦產品：白鯨防水壁...,❌ FAIL,[]
23,產品型號查詢,請問有推薦的「LED燈 50Wx1 壁投式」產品嗎？,推薦型號為：舞光/OD-FLZ50DR1 舞-50W 宙斯泛光燈 65K,- **需求判斷**：您在找的是「特定規格/型式」的產品——**LED燈 50W ×1、壁投式（壁面投射/壁面照明）**。\n\n- **目錄符合度說明**： \n - 抱歉，目前的產品目...,❌ FAIL,[]
24,產品型號查詢,請問有推薦的「LED燈 10Wx1 嵌入式」產品嗎？,"推薦型號為：舞光/DL-51040-LO+10W 舞-E27 15"" 橫崁+玻+10W",- **需求判斷**\n - 你在找的是「**10W、單燈(10Wx1)、嵌入式(崁燈)**」類型。\n - 但依目前目錄內容來看：**有 10W 的筒燈產品**，不過它屬於「**吸頂筒燈...,❌ FAIL,[]
25,產品型號查詢,請問有推薦的「LED燈 10Wx1 吸頂式」產品嗎？,推薦型號為：舞光/EC-806+D-E2710WR10 舞-白筒燈 17X19CM+10W,您要找的是「10W、單顆(10Wx1)、吸頂式」的產品型號；依目錄內容，目前最符合的是 **「10W 神盾吸頂筒燈」(LED-CEA10 系列)**，可依色溫與燈體顏色選擇：\n\n- **1...,❌ FAIL,[]
26,產品型號查詢,請問有推薦的「LED燈 9Wx1 照樹燈」產品嗎？,推薦型號為：舞光/OD-3174R1 舞-9W 照樹燈 30K 35°,- **需求判斷**：您是在找「**9W×1 的照樹燈**」這種**特定瓦數規格**的產品。 \n - 目前目錄文字有提到「**9W 適裝於矮樹叢**」的建議，但**未提供對應的 9W 產...,❌ FAIL,[]
27,產品型號查詢,請問有推薦的「LED燈 10Wx1 草皮燈」產品嗎？,推薦型號為：舞光/OD-3168R2 舞-10W 馬克草皮燈 80CM 30K,- **需求判斷**：您指定找「**10W×1 的LED草皮燈**」屬於**特定規格/功率需求**。依目錄內容，目前符合 **10W** 的草皮燈為「**肯特草皮燈**」系列（提供不同高度可選...,❌ FAIL,[]
28,產品型號查詢,請問有推薦的「LED燈 25Wx1 高燈」產品嗎？,推薦型號為：舞光/OD-1034R1+D-E2725WR3 舞-E27X1 高燈+25W,- **需求判斷**：您在找「**25W ×1**」的單燈（多半是 **E27 單顆燈泡**搭配吊掛/高燈燈具使用）。目錄中最符合的是 **E27 25W 燈泡**系列；若您指的是倉庫用「高天...,❌ FAIL,[]

In [5]:
import pandas as pd
import os
import time
from tqdm import tqdm
from collections import Counter
from docling_rag_v5 import RAGSystem, Config

# ==========================================
# 1. Setup & Initialization
# ==========================================
config = Config(
    pdf_path="2025舞光LED21st(單頁水印可搜尋).pdf",
    force_reparse=False
)

print("🚀 Initializing RAG System...")
rag = RAGSystem(config)
rag.initialize()
print("✅ System Ready.")

# ==========================================
# 2. Configuration & Target Selection
# ==========================================
csv_file = "test_data.csv"
TEST_ITERATIONS = 100  # Number of times to repeat the test

if not os.path.exists(csv_file):
    print(f"❌ Error: '{csv_file}' not found.")
    exit()

df = pd.read_csv(csv_file)

# Select the target request (Default: The first row of the CSV)
# You can change index [0] to any other row index to test a different query
target_row = df.iloc[0]
test_request = str(target_row['request'])
expected_product = str(target_row['product'])

print("\n" + "="*50)
print(f"🎯 TARGET REQUEST: \"{test_request}\"")
print(f"👀 EXPECTED INFO:  \"{expected_product}\"")
print(f"🔄 LOOPS:          {TEST_ITERATIONS}")
print("="*50 + "\n")

# ==========================================
# 3. Consistency Loop
# ==========================================
answers = []
execution_times = []

print("🧪 Running consistency check...")

for i in tqdm(range(TEST_ITERATIONS)):
    start_time = time.time()
    
    try:
        # --- QUERY THE AI ---
        response = rag.query(test_request)
        answer_text = response['answer'].strip() # Strip whitespace for fair comparison
        
        answers.append(answer_text)
        
    except Exception as e:
        answers.append(f"ERROR: {str(e)}")
    
    end_time = time.time()
    execution_times.append(end_time - start_time)

# ==========================================
# 4. Analysis & Reporting
# ==========================================

# Count occurrences of each unique answer
counter = Counter(answers)
most_common_answer, most_common_count = counter.most_common(1)[0]
consistency_score = (most_common_count / TEST_ITERATIONS) * 100
avg_time = sum(execution_times) / len(execution_times)

print("\n" + "="*50)
print(f"📊 CONSISTENCY REPORT")
print("="*50)
print(f"Total Runs:        {TEST_ITERATIONS}")
print(f"Unique Variations: {len(counter)}")
print(f"Consistency Score: {consistency_score:.1f}% (Frequency of dominant answer)")
print(f"Avg Response Time: {avg_time:.2f}s")
print("-" * 50)

print("\n🔍 DETAILED VARIATIONS:")

# Display all unique answers found and their frequency
for idx, (answer, count) in enumerate(counter.items(), 1):
    percentage = (count / TEST_ITERATIONS) * 100
    print(f"\n[Variation {idx}] - Appeared {count} times ({percentage:.1f}%)")
    print(f"Answer: {answer}")
    
    # Check if this variation contains the expected product info
    # We clean the string for a loose check
    clean_expected = expected_product.replace("舞光/", "").split(" ")[0] # Grab just the model number roughly
    if clean_expected.lower() in answer.lower():
        print("✅ Contains expected model number")
    else:
        print("⚠️ DOES NOT contain expected model number")

# ==========================================
# 5. Save Raw Data
# ==========================================
# Create a DataFrame to save every single run for debugging
log_df = pd.DataFrame({
    "iteration": range(1, TEST_ITERATIONS + 1),
    "request": test_request,
    "response": answers,
    "execution_time": execution_times
})

output_filename = "consistency_test_results.csv"
log_df.to_csv(output_filename, index=False)
print(f"\n📝 Full logs saved to: {output_filename}")

🚀 Initializing RAG System...
Initializing...
Loaded 388 pages from cache
Ready: 388 pages indexed
✅ System Ready.

==================================================
🎯 TARGET REQUEST: "LED燈 35Wx1 嵌入式 220V"
👀 EXPECTED INFO:  "舞光/D-PD25D-EGR1"
🔄 LOOPS:          100
==================================================

🧪 Running consistency check...

Batches: 100%|██████████| 1/1 [00:00<00:00, 21.99it/s]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.90it/s]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.30s/it]
  1%|          | 1/100 [00:32<53:27, 32.40s/it]

KeyboardInterrupt:

In [1]:
import pandas as pd
import os
import time
from tqdm import tqdm
from collections import Counter
from docling_rag_v5 import RAGSystem, Config

# ==========================================
# 1. Setup & Initialization
# ==========================================
config = Config(
    pdf_path="2025舞光LED21st(單頁水印可搜尋).pdf",
    force_reparse=False
)

print("🚀 Initializing RAG System...")
rag = RAGSystem(config)
rag.initialize()
print("✅ System Ready.")

# ==========================================
# 2. Configuration
# ==========================================
csv_file = "test_data.csv"
TEST_ITERATIONS = 100  # How many times to test EACH row

if not os.path.exists(csv_file):
    print(f"❌ Error: '{csv_file}' not found.")
    exit()

df = pd.read_csv(csv_file)
print(f"📂 Loaded {len(df)} test cases.")
print(f"🔄 Total Queries to run: {len(df) * TEST_ITERATIONS}")

# ==========================================
# 3. Main Evaluation Loop
# ==========================================
summary_results = []

# OUTER LOOP: Iterate through each row in the CSV
for index, row in df.iterrows():
    user_request = str(row['request'])
    expected_product = str(row['product'])
    
    # We clean the expected model for comparison (remove brand name, whitespace)
    target_model_key = expected_product.replace("舞光/", "").split(" ")[0].strip()

    print(f"\n[{index+1}/{len(df)}] Testing: {user_request}")
    
    current_row_answers = []
    start_time = time.time()

    # INNER LOOP: Run 100 times for this specific row
    for i in tqdm(range(TEST_ITERATIONS), desc=f"   ↳ Repeating {TEST_ITERATIONS} times", leave=False):
        try:
            response = rag.query(user_request)
            answer_text = response['answer'].strip()
            current_row_answers.append(answer_text)
        except Exception as e:
            current_row_answers.append(f"ERROR: {str(e)}")

    duration = time.time() - start_time
    
    # ==========================================
    # 4. Analyze Results for this Row
    # ==========================================
    counter = Counter(current_row_answers)
    
    # Find the most frequent answer the AI gave
    most_common_answer, most_common_count = counter.most_common(1)[0]
    
    # Calculate Consistency: How often did it give the EXACT same dominant answer?
    consistency_score = (most_common_count / TEST_ITERATIONS) * 100
    
    # Calculate Accuracy: Did the dominant answer contain the expected model number?
    is_accurate = target_model_key.lower() in most_common_answer.lower()
    
    # Add to summary list
    summary_results.append({
        "row_id": index + 1,
        "request": user_request,
        "expected_product": expected_product,
        "most_common_answer": most_common_answer,
        "consistency_score_pct": consistency_score, # How stable the answer was
        "accuracy_pass": "✅ PASS" if is_accurate else "❌ FAIL", # If the stable answer was correct
        "unique_variations": len(counter), # How many different answers it hallucinated
        "avg_time_per_query": round(duration / TEST_ITERATIONS, 3)
    })

# ==========================================
# 5. Final Reporting
# ==========================================
results_df = pd.DataFrame(summary_results)

# Print a nice table to the console
print("\n" + "="*80)
print(f"📊 FINAL REPORT (Summary by Row)")
print("="*80)
# Adjust pandas display to show columns clearly
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# Display specific columns for quick reading
print(results_df[['row_id', 'request', 'consistency_score_pct', 'accuracy_pass', 'unique_variations']])

# Save to CSV
output_filename = "full_consistency_report.csv"
results_df.to_csv(output_filename, index=False)
print(f"\n📝 Detailed report saved to: {output_filename}")

/Users/max/Desktop/python_codes/DanceLight--LED-AI-Chatbot-and-attribute-searching_v2/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

🚀 Initializing RAG System...
Devices: Embedding(cpu) / Reranker(mps)
Initializing...
Loaded 388 pages from cache
Ready: 388 pages indexed
✅ System Ready.
📂 Loaded 21 test cases.
🔄 Total Queries to run: 2100

[1/21] Testing: LED燈 35Wx1 嵌入式 220V

Batches: 100%|██████████| 1/1 [00:01<00:00,  1.18s/it]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:13<00:00,  2.79s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.38it/s]5<58:06, 35.21s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.22s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]9<47:29, 29.07s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]3<50:07, 31.00s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.18s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.04it/s]0<47:04, 29.43s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.19s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]6<44:29, 28.10s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.28it/s]3<43:47, 27.96s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.18s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.99it/s]8<41:36, 26.85s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]4<41:00, 26.75s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]4<41:50, 27.58s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.56s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]44<42:44, 28.50s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.90it/s]10<40:59, 27.64s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.18s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]41<42:14, 28.80s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.58it/s]04<39:08, 26.99s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.18s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.64it/s]48<45:52, 32.00s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.08s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.10it/s]20<45:34, 32.18s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.30s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]51<44:23, 31.71s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.21s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.91it/s]18<41:58, 30.34s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.07s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.11it/s]42<38:49, 28.41s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]10<38:10, 28.28s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.55it/s]37<37:12, 27.91s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.17s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.19it/s]27<45:35, 34.63s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.20it/s]50<40:28, 31.14s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.03it/s]10<35:29, 27.65s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.16it/s]42<36:45, 29.02s/it]
Batches: 100%|██████████| 5/5 [00:13<00:00,  2.69s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  3.30it/s]28<42:45, 34.21s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.62it/s]49<37:15, 30.20s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  1.99s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.15it/s]12<33:55, 27.88s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.67it/s]39<33:08, 27.62s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  1.99s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.80it/s]00<30:28, 25.76s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  2.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.73it/s]23<28:57, 24.83s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  1.99s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.82it/s]45<27:28, 23.90s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.48it/s]07<26:30, 23.39s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.07s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.39it/s]29<25:37, 22.95s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.29it/s]54<25:56, 23.59s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.08s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.71it/s]16<24:59, 23.08s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.20s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.25it/s]38<24:29, 22.96s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.38s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.63it/s]02<24:13, 23.08s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.42s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.15it/s]24<23:39, 22.89s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.53s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.75it/s]00<27:06, 26.66s/it]
Batches: 100%|██████████| 5/5 [00:17<00:00,  3.52s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  2.44it/s]31<27:56, 27.94s/it]
Batches: 100%|██████████| 5/5 [00:16<00:00,  3.26s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  2.42it/s]58<27:11, 27.66s/it]
Batches: 100%|██████████| 5/5 [00:14<00:00,  2.80s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]23<26:07, 27.02s/it]
Batches: 100%|██████████| 5/5 [00:13<00:00,  2.70s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]47<24:54, 26.23s/it]
Batches: 100%|██████████| 5/5 [00:16<00:00,  3.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.40it/s]17<25:24, 27.22s/it]
Batches: 100%|██████████| 5/5 [00:14<00:00,  2.87s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  3.70it/s]41<24:11, 26.38s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.55s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]06<23:18, 25.90s/it]
Batches: 100%|██████████| 5/5 [00:16<00:00,  3.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.70it/s]35<23:34, 26.68s/it]
Batches: 100%|██████████| 5/5 [00:17<00:00,  3.43s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.33it/s]02<23:10, 26.73s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.43s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.09it/s]26<22:09, 26.07s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]44<19:43, 23.67s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.48s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.60it/s]06<18:46, 22.99s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.49s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]25<17:35, 21.99s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.52s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]44<16:27, 21.01s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  1.95s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  1.41it/s]12<17:41, 23.07s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.57it/s]35<17:18, 23.07s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 26.69it/s]50<15:16, 20.82s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.29s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.96it/s]08<14:09, 19.76s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.44it/s]24<13:00, 18.57s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.61it/s]43<12:50, 18.80s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.30s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.29it/s]02<12:32, 18.81s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.29s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 26.32it/s]16<11:21, 17.47s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.29s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]36<11:32, 18.23s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.43it/s]56<11:38, 18.87s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.39it/s]15<11:11, 18.65s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.96it/s]32<10:37, 18.22s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.75it/s]50<10:18, 18.20s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]06<09:37, 17.51s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.00it/s]22<09:04, 17.02s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.29s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.39it/s]39<08:47, 17.00s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.06it/s]55<08:21, 16.72s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.39it/s]18<09:03, 18.74s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.05it/s]34<08:24, 18.01s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.55it/s]56<08:36, 19.14s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.80it/s]12<07:48, 18.03s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.30s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]30<07:33, 18.14s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.29s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.40it/s]47<07:09, 17.88s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.48it/s]06<06:56, 18.10s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.29s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.79it/s]25<06:44, 18.39s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.29s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.00it/s]48<06:56, 19.83s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.68it/s]08<06:35, 19.79s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.29s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]28<06:14, 19.73s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.91it/s]50<06:08, 20.46s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.18it/s]10<05:48, 20.50s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.74it/s]33<05:36, 21.06s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.81it/s]57<05:32, 22.14s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.20it/s]20<05:13, 22.40s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.73it/s]41<04:43, 21.80s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.38it/s]05<04:28, 22.41s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.29it/s]27<04:05, 22.31s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.72it/s]47<03:35, 21.58s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.30it/s]06<03:07, 20.82s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.04it/s]24<02:40, 20.11s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.65it/s]03<03:00, 25.74s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.29it/s]24<02:25, 24.28s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.42it/s]47<01:59, 23.99s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 26.13it/s]07<01:30, 22.62s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.55it/s]26<01:05, 21.77s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.30s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.44it/s]46<00:42, 21.20s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.29s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]06<00:20, 20.87s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.29s/it]

[2/21] Testing: LED燈 20Wx1 吊管式 220V

Batches: 100%|██████████| 1/1 [00:00<00:00, 17.93it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.61it/s]2<37:10, 22.53s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]6<38:34, 23.61s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]1<38:42, 23.95s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.07s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.74it/s]2<36:52, 23.05s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.70it/s]1<34:03, 21.51s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.99it/s]0<32:04, 20.48s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.44it/s]9<31:14, 20.15s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.58it/s]4<33:19, 21.74s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.47it/s]2<31:06, 20.51s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.06s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.12it/s]47<37:25, 24.95s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.84it/s]03<33:00, 22.25s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.20it/s]36<37:15, 25.40s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]51<32:28, 22.40s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.74it/s]06<28:45, 20.07s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.25it/s]23<27:20, 19.31s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.60it/s]40<25:40, 18.34s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.08s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.41it/s]57<24:56, 18.04s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.08s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.51it/s]14<24:11, 17.71s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]33<24:34, 18.20s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.74it/s]51<24:14, 18.18s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.82it/s]07<23:03, 17.51s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.29it/s]25<22:46, 17.52s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.95it/s]46<23:51, 18.59s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.36it/s]07<24:37, 19.44s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.07s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.50it/s]26<23:57, 19.17s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.23it/s]44<23:05, 18.72s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.08s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.01it/s]01<22:11, 18.24s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.20s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.96it/s]18<21:40, 18.06s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.42it/s]36<21:07, 17.85s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.48it/s]57<22:05, 18.94s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.27it/s]19<22:49, 19.85s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.15it/s]43<23:58, 21.16s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]02<22:53, 20.50s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.51s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.78it/s]25<23:20, 21.22s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.29s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]51<24:38, 22.74s/it]
Batches: 100%|██████████| 5/5 [00:08<00:00,  1.77s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.22it/s]17<25:05, 23.53s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.48it/s]38<24:00, 22.86s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.29s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.33it/s]55<21:55, 21.22s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.48s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]17<21:30, 21.16s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.17s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]37<21:05, 21.09s/it]
Batches: 100%|██████████| 5/5 [00:08<00:00,  1.62s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.03it/s]56<20:05, 20.43s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.19s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.39it/s]16<19:27, 20.13s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.19s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.30it/s]33<18:20, 19.30s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.02it/s]56<18:59, 20.35s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.67it/s]24<20:41, 22.57s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.53it/s]52<21:56, 24.39s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.84it/s]07<18:54, 21.41s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.70it/s]23<17:08, 19.78s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.56it/s]37<15:20, 18.05s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.70it/s]52<14:19, 17.20s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.00it/s]07<13:31, 16.55s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.20s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.31it/s]26<13:53, 17.37s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.24it/s]41<12:58, 16.56s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.53it/s]54<11:56, 15.57s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.30it/s]08<11:12, 14.94s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.40it/s]25<11:25, 15.59s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.14it/s]44<11:57, 16.70s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.96it/s]59<11:20, 16.21s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.08s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.45it/s]16<11:11, 16.38s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.08s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.36it/s]31<10:45, 16.13s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.63it/s]48<10:32, 16.22s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.35it/s]11<11:29, 18.14s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.74it/s]25<10:29, 17.03s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.06s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.60it/s]44<10:30, 17.51s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.39it/s]03<10:30, 18.01s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.58it/s]18<09:43, 17.17s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.07s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.24it/s]37<09:40, 17.59s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.06s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.71it/s]58<10:02, 18.83s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.07s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]16<09:30, 18.40s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.20it/s]33<08:59, 18.00s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.15it/s]52<08:53, 18.39s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.25it/s]07<08:05, 17.35s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.06s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.91it/s]22<07:32, 16.76s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]42<07:38, 17.65s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.06s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.43it/s]00<07:22, 17.71s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.53it/s]20<07:22, 18.45s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.22it/s]36<06:47, 17.71s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.08s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]54<06:29, 17.70s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.99it/s]20<07:05, 20.25s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.31it/s]38<06:34, 19.73s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.20it/s]54<05:50, 18.43s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.13it/s]14<05:41, 18.95s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.36it/s]29<05:02, 17.80s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.54it/s]46<04:41, 17.62s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.01it/s]04<04:26, 17.77s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.99it/s]22<04:09, 17.84s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.50it/s]35<03:29, 16.11s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.15it/s]50<03:10, 15.91s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]02<02:43, 14.86s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.21it/s]17<02:28, 14.88s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.16it/s]41<02:36, 17.42s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.42it/s]57<02:17, 17.15s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.37it/s]17<02:06, 18.09s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.38it/s]40<01:57, 19.53s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.48it/s]55<01:30, 18.19s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.06s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.13it/s]11<01:09, 17.34s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]33<00:56, 18.92s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.57it/s]50<00:36, 18.22s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.05it/s]08<00:18, 18.10s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]

[3/21] Testing: LED燈 20Wx1 吸頂式 220V

Batches: 100%|██████████| 1/1 [00:00<00:00, 18.36it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.40s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.23it/s]3<39:33, 23.97s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.40s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  2.63it/s]7<39:05, 23.93s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.37s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.11it/s]8<36:16, 22.43s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.20it/s]7<33:38, 21.02s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.71it/s]6<31:56, 20.18s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.47s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.60it/s]9<33:34, 21.43s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.63it/s]9<32:02, 20.68s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.38s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]3<28:53, 18.84s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.83it/s]6<30:22, 20.03s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.42s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.51it/s]23<28:33, 19.04s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.46it/s]41<27:39, 18.64s/it]
Batches: 100%|██████████| 5/5 [03:10<00:00, 38.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.53it/s]03<1:49:11, 74.45s/it]
Batches: 100%|██████████| 5/5 [00:23<00:00,  4.80s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.87it/s]36<1:29:54, 62.01s/it]
Batches: 100%|██████████| 5/5 [00:21<00:00,  4.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.57it/s]07<1:15:27, 52.64s/it]
Batches: 100%|██████████| 5/5 [00:21<00:00,  4.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.52it/s]37<1:05:01, 45.90s/it]
Batches: 100%|██████████| 5/5 [00:21<00:00,  4.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.60it/s]24<1:04:43, 46.23s/it]
Batches: 100%|██████████| 5/5 [00:33<00:00,  6.61s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  3.77it/s]10<1:03:46, 46.10s/it]
Batches: 100%|██████████| 5/5 [00:23<00:00,  4.78s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.01it/s]18<1:11:53, 52.60s/it]
Batches: 100%|██████████| 5/5 [03:42<00:00, 44.50s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.82it/s]10<2:23:43, 106.46s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  1.84s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]27<1:46:06, 79.58s/it]
Batches: 100%|██████████| 5/5 [00:08<00:00,  1.65s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.30it/s]51<1:23:05, 63.10s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  1.97s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.63it/s]11<1:04:58, 49.98s/it]
Batches: 100%|██████████| 5/5 [00:17<00:00,  3.43s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]41<56:20, 43.90s/it]
Batches: 100%|██████████| 5/5 [00:16<00:00,  3.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.41it/s]12<50:45, 40.08s/it]
Batches: 100%|██████████| 5/5 [00:18<00:00,  3.69s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.57it/s]43<46:51, 37.49s/it]
Batches: 100%|██████████| 5/5 [15:17<00:00, 183.50s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.79it/s]16<6:17:40, 306.23s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.48it/s]38<4:28:34, 220.75s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.38s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]04<3:14:57, 162.47s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.21s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  3.04it/s]32<2:24:18, 121.95s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.61it/s]52<1:46:35, 91.36s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.37s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]15<1:21:40, 71.03s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.38it/s]36<1:03:30, 56.04s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.08s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.72it/s]59<51:33, 46.17s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.92it/s]20<42:22, 38.53s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.40it/s]44<37:01, 34.17s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]09<33:25, 31.34s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.13it/s]30<29:44, 28.33s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.12it/s]53<27:32, 26.65s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.25s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.93it/s]15<25:46, 25.35s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  1.91s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]47<27:19, 27.33s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.45it/s]07<24:40, 25.09s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.96it/s]30<23:32, 24.36s/it]
Batches: 100%|██████████| 5/5 [00:08<00:00,  1.65s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.53it/s]50<21:58, 23.13s/it]
Batches: 100%|██████████| 5/5 [00:21<00:00,  4.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.84it/s]26<25:07, 26.91s/it]
Batches: 100%|██████████| 5/5 [00:21<00:00,  4.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.09it/s]04<27:48, 30.33s/it]
Batches: 100%|██████████| 5/5 [00:13<00:00,  2.70s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.57it/s]28<25:39, 28.50s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  1.92s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.26it/s]48<22:53, 25.92s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.50it/s]08<20:49, 24.02s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.21s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]25<18:48, 22.12s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.37s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]45<17:50, 21.41s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.47it/s]08<17:57, 21.99s/it]
Batches: 100%|██████████| 5/5 [00:22<00:00,  4.57s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.55it/s]57<24:00, 30.02s/it]
Batches: 100%|██████████| 5/5 [00:14<00:00,  2.82s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.21it/s]24<22:40, 28.95s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.08s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.54it/s]44<20:17, 26.46s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.72it/s]07<18:58, 25.31s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.07s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.47it/s]30<18:01, 24.57s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]53<17:15, 24.08s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.48s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.54it/s]17<16:49, 24.04s/it]
Batches: 100%|██████████| 5/5 [00:22<00:00,  4.56s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.54it/s]54<19:03, 27.89s/it]
Batches: 100%|██████████| 5/5 [00:21<00:00,  4.26s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.54it/s]39<22:01, 33.04s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]59<18:55, 29.12s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  1.89s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.50it/s]19<16:46, 26.50s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.53it/s]40<15:19, 24.84s/it]
Batches: 100%|██████████| 5/5 [00:21<00:00,  4.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.46it/s]17<17:10, 28.64s/it]
Batches: 100%|██████████| 5/5 [00:22<00:00,  4.59s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.40it/s]56<18:23, 31.53s/it]
Batches: 100%|██████████| 5/5 [00:08<00:00,  1.75s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.13it/s]20<16:36, 29.31s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.08s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]40<14:38, 26.61s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.21s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.62it/s]03<13:37, 25.55s/it]
Batches: 100%|██████████| 5/5 [00:14<00:00,  2.85s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.61it/s]32<13:45, 26.63s/it]
Batches: 100%|██████████| 5/5 [00:21<00:00,  4.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.54it/s]09<14:51, 29.72s/it]
Batches: 100%|██████████| 5/5 [00:19<00:00,  3.92s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.80it/s]39<14:22, 29.72s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.42s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.81it/s]05<13:17, 28.49s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.23s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.25it/s]27<11:58, 26.62s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]51<11:12, 25.87s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.52s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]17<10:43, 25.76s/it]
Batches: 100%|██████████| 5/5 [00:14<00:00,  2.91s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.47it/s]58<12:12, 30.50s/it]
Batches: 100%|██████████| 5/5 [00:21<00:00,  4.21s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.65it/s]30<11:51, 30.94s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.54s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.06it/s]10<12:22, 33.76s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 27.14it/s]30<10:16, 29.36s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.24s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.93it/s]50<08:53, 26.65s/it]
Batches: 100%|██████████| 5/5 [00:13<00:00,  2.73s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 27.05it/s]14<08:13, 25.97s/it]
Batches: 100%|██████████| 5/5 [00:13<00:00,  2.65s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.59it/s]44<08:07, 27.08s/it]
Batches: 100%|██████████| 5/5 [00:21<00:00,  4.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.38it/s]18<08:16, 29.22s/it]
Batches: 100%|██████████| 5/5 [00:24<00:00,  4.90s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]54<08:18, 31.15s/it]
Batches: 100%|██████████| 5/5 [00:15<00:00,  3.18s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.42it/s]25<07:46, 31.11s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.49s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.63it/s]51<06:57, 29.79s/it]
Batches: 100%|██████████| 5/5 [00:13<00:00,  2.70s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.48it/s]0:17<06:11, 28.59s/it]
Batches: 100%|██████████| 5/5 [00:14<00:00,  2.86s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.15it/s]0:45<05:38, 28.22s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.59s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]1:08<04:55, 26.85s/it]
Batches: 100%|██████████| 5/5 [00:13<00:00,  2.77s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.49it/s]1:35<04:28, 26.82s/it]
Batches: 100%|██████████| 5/5 [00:17<00:00,  3.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.58it/s]2:03<04:04, 27.13s/it]
Batches: 100%|██████████| 5/5 [00:14<00:00,  2.81s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.59it/s]2:28<03:32, 26.61s/it]
Batches: 100%|██████████| 5/5 [00:23<00:00,  4.61s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.77it/s]3:08<03:34, 30.68s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.34s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]3:25<02:38, 26.38s/it]
Batches: 100%|██████████| 5/5 [00:13<00:00,  2.69s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.63it/s]3:51<02:11, 26.24s/it]
Batches: 100%|██████████| 5/5 [00:21<00:00,  4.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.56it/s]4:29<01:59, 29.98s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]4:52<01:23, 27.68s/it]
Batches: 100%|██████████| 5/5 [00:16<00:00,  3.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.55it/s]5:25<00:58, 29.26s/it]
Batches: 100%|██████████| 5/5 [00:21<00:00,  4.26s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]6:09<00:33, 33.65s/it]
Batches: 100%|██████████| 5/5 [00:18<00:00,  3.67s/it]

[4/21] Testing: LED燈 20Wx1 壁式 220V

Batches: 100%|██████████| 1/1 [00:00<00:00, 19.13it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:08<00:00,  1.65s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.82it/s]1<36:00, 21.82s/it]
Batches: 100%|██████████| 5/5 [00:08<00:00,  1.67s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.06it/s]1<33:32, 20.54s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.51s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]1<32:51, 20.32s/it]
Batches: 100%|██████████| 5/5 [00:08<00:00,  1.74s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]2<39:19, 24.58s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.92it/s]9<34:29, 21.78s/it]
Batches: 100%|██████████| 5/5 [00:08<00:00,  1.74s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.28it/s]9<33:22, 21.30s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  1.83s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]8<31:51, 20.55s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  1.99s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.67it/s]9<31:45, 20.71s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.30it/s]2<32:10, 21.21s/it]
Batches: 100%|██████████| 5/5 [00:08<00:00,  1.79s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.61it/s]37<33:39, 22.44s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  1.84s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.12it/s]02<34:18, 23.13s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]22<32:38, 22.26s/it]
Batches: 100%|██████████| 5/5 [00:08<00:00,  1.72s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.54it/s]42<31:26, 21.69s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  1.96s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 26.06it/s]02<30:25, 21.23s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]25<30:47, 21.73s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  1.92s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]45<29:46, 21.26s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.07s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]12<31:29, 22.76s/it]
Batches: 100%|██████████| 5/5 [00:08<00:00,  1.62s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]37<56:37, 41.43s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.37s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.54it/s]59<48:03, 35.60s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  1.88s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]21<42:18, 31.74s/it]
Batches: 100%|██████████| 5/5 [00:08<00:00,  1.68s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.70it/s]43<37:54, 28.79s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.37s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]02<33:32, 25.80s/it]
Batches: 100%|██████████| 5/5 [00:08<00:00,  1.70s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.56it/s]22<30:42, 23.93s/it]
Batches: 100%|██████████| 5/5 [00:08<00:00,  1.78s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.24it/s]43<29:18, 23.14s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.68it/s]01<27:09, 21.73s/it]
Batches: 100%|██████████| 5/5 [00:08<00:00,  1.77s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.37it/s]26<27:48, 22.55s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.50s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 28.06it/s]57<30:27, 25.04s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.28it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.16it/s]13<26:57, 22.47s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.26s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.51it/s]35<26:19, 22.25s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.21it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.23it/s]51<23:50, 20.44s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]13<23:58, 20.85s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]30<22:29, 19.85s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.65it/s]54<23:20, 20.91s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.33it/s]16<23:17, 21.17s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.55it/s]33<21:49, 20.15s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]47<19:31, 18.31s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]01<17:52, 17.03s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]24<19:11, 18.57s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.79it/s]39<17:45, 17.47s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.30it/s]54<16:52, 16.88s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.51it/s]16<18:11, 18.50s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.62it/s]40<19:29, 20.17s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.14it/s]02<19:28, 20.50s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.46it/s]32<21:52, 23.43s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.89it/s]50<20:02, 21.86s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.81it/s]08<18:43, 20.80s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]23<16:35, 18.79s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.04it/s]43<16:45, 19.35s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]11<18:34, 21.85s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.27it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]27<16:47, 20.16s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.74it/s]49<16:51, 20.65s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.62it/s]06<15:46, 19.71s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.77it/s]24<14:51, 18.98s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.54it/s]38<13:25, 17.52s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.47it/s]53<12:33, 16.74s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.80it/s]14<13:20, 18.19s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.20it/s]47<16:05, 22.45s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.23it/s]01<13:59, 19.98s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]17<12:52, 18.84s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.48it/s]42<13:43, 20.59s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.17it/s]56<12:03, 18.56s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.72it/s]24<13:32, 21.39s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.15it/s]50<14:12, 23.05s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.28it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.95it/s]04<12:09, 20.28s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.00it/s]23<11:31, 19.75s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.15it/s]47<12:00, 21.20s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.06it/s]05<11:03, 20.11s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.28it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.15it/s]19<09:49, 18.44s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.51it/s]40<09:49, 19.00s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]53<08:41, 17.38s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]09<08:05, 16.73s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.74it/s]23<07:25, 15.91s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.82it/s]36<06:52, 15.29s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.63it/s]49<06:13, 14.35s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.74it/s]16<07:38, 18.34s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.27it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.82it/s]29<06:40, 16.69s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.50it/s]42<06:00, 15.69s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.79it/s]56<05:30, 15.01s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.53it/s]15<05:43, 16.34s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.84it/s]32<05:31, 16.56s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]51<05:29, 17.32s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]05<04:48, 16.05s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.41it/s]17<04:13, 14.92s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.58it/s]39<04:35, 17.21s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.23it/s]05<04:53, 19.59s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.27it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]21<04:20, 18.61s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.61it/s]39<04:00, 18.53s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.26it/s]52<03:23, 16.94s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.38it/s]10<03:09, 17.19s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.76it/s]29<02:56, 17.66s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.20it/s]45<02:34, 17.17s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]00<02:12, 16.57s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.42it/s]17<01:55, 16.56s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.49it/s]34<01:40, 16.70s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.27it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.54it/s]47<01:19, 15.80s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.48it/s]02<01:01, 15.36s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.12it/s]15<00:44, 14.74s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.73it/s]33<00:31, 15.73s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.36it/s]49<00:15, 15.68s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

[5/21] Testing: LED燈 15Wx1 嵌入式 220V

Batches: 100%|██████████| 1/1 [00:00<00:00, 22.11it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.20s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]6<26:55, 16.32s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.17s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]4<28:38, 17.54s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.17s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.66it/s]1<28:02, 17.35s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.18s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.36it/s]9<28:02, 17.52s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.19s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]8<28:44, 18.15s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.17s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.39it/s]7<28:51, 18.42s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.69it/s]6<28:39, 18.49s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.89it/s]2<31:51, 20.78s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.17s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.44it/s]2<31:19, 20.66s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.51it/s]10<29:54, 19.94s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.92it/s]31<29:42, 20.03s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.80it/s]48<28:01, 19.11s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.43it/s]06<27:15, 18.80s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.28it/s]23<26:08, 18.24s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.54it/s]43<26:39, 18.82s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.84it/s]02<26:27, 18.90s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.94it/s]22<26:37, 19.25s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.85it/s]40<25:43, 18.82s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]00<25:54, 19.20s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.25it/s]13<23:12, 17.41s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]33<23:50, 18.11s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.83it/s]51<23:44, 18.27s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]07<22:14, 17.33s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.66it/s]24<21:55, 17.31s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.17s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]40<21:11, 16.96s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.64it/s]53<19:33, 15.86s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.43it/s]12<20:12, 16.60s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.42it/s]29<20:10, 16.81s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.19s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]45<19:37, 16.58s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]07<21:24, 18.35s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.46it/s]45<27:45, 24.14s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.17s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.64it/s]11<28:00, 24.71s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.24it/s]30<25:38, 22.96s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]50<24:25, 22.20s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.60it/s]08<22:34, 20.84s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.81it/s]27<21:42, 20.35s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]56<24:06, 22.97s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.17s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.93it/s]30<26:55, 26.06s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.47it/s]50<24:38, 24.24s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]20<26:08, 26.15s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.17s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.54it/s]45<25:09, 25.59s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.04it/s]25<28:54, 29.91s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.19s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]52<27:49, 29.29s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.29s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]15<25:20, 27.16s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]50<27:08, 29.61s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.07it/s]10<24:10, 26.87s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.26it/s]36<23:30, 26.61s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.18s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]04<23:14, 26.82s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.95it/s]30<22:37, 26.61s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.90it/s]59<22:44, 27.29s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.01it/s]22<21:19, 26.11s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.00it/s]45<20:07, 25.16s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.16it/s]05<18:36, 23.76s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.81it/s]23<16:52, 22.00s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.27it/s]45<16:24, 21.88s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.81it/s]06<15:55, 21.71s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.17s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.13it/s]25<14:57, 20.88s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.59it/s]54<16:14, 23.21s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.74it/s]15<15:24, 22.55s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]45<16:32, 24.82s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.15it/s]08<15:42, 24.18s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]29<14:49, 23.39s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.69it/s]56<15:00, 24.33s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.47it/s]19<14:27, 24.09s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.07it/s]44<14:13, 24.38s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]06<13:24, 23.67s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.17s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.79it/s]28<12:36, 22.91s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.33it/s]48<11:52, 22.27s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.49it/s]10<11:29, 22.23s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.14it/s]30<10:44, 21.48s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.20s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.83it/s]51<10:17, 21.29s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.51it/s]13<10:02, 21.53s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.80it/s]38<10:12, 22.69s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.53it/s]06<10:28, 24.17s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.85it/s]35<10:41, 25.66s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.75it/s]53<09:19, 23.32s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.48it/s]17<08:56, 23.34s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.43it/s]39<08:25, 22.96s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.81it/s]58<07:41, 21.96s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.27it/s]23<07:35, 22.79s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.44it/s]43<06:57, 22.00s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.02it/s]06<06:41, 22.31s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.39it/s]26<06:04, 21.47s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.07it/s]42<05:17, 19.86s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.61it/s]08<05:25, 21.69s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.21s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.84it/s]34<05:21, 22.96s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.34it/s]54<04:48, 22.21s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]21<04:44, 23.73s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.95it/s]44<04:17, 23.45s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.17s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.77it/s]09<03:59, 23.98s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.81it/s]30<03:26, 22.89s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.79it/s]44<02:41, 20.20s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.45it/s]02<02:16, 19.52s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.68it/s]21<01:56, 19.36s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.17s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.82it/s]46<01:46, 21.32s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.18s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.73it/s]07<01:24, 21.10s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.46it/s]29<01:04, 21.44s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]3:58<23:35, 707.64s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.37s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  3.30it/s]4:16<08:20, 500.75s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.30s/it]

[6/21] Testing: LED 燈 13Wx2 壁式 220V

Batches: 100%|██████████| 1/1 [00:00<00:00, 16.75it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.64it/s]2<21:00, 12.74s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.25it/s]8<24:04, 14.74s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.46it/s]4<24:43, 15.30s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.53it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.89it/s]9<24:11, 15.12s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.33it/s]3<23:23, 14.78s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.15it/s]1<24:56, 15.92s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.57it/s]5<23:22, 15.08s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]0<23:18, 15.20s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.64it/s]5<22:55, 15.11s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.55it/s]32<23:29, 15.66s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.50it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.34it/s]48<23:29, 15.84s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.54it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.57it/s]02<22:25, 15.29s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.35it/s]16<21:21, 14.73s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.66it/s]29<20:38, 14.40s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.14it/s]46<21:29, 15.17s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.52it/s]00<20:33, 14.68s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.73it/s]15<20:27, 14.79s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]27<18:58, 13.89s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.49it/s]39<17:58, 13.31s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.54it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.30it/s]51<17:19, 13.00s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.94it/s]03<16:48, 12.76s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.50it/s]15<16:15, 12.51s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.21it/s]34<18:29, 14.41s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.54it/s]48<18:07, 14.31s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.46it/s]15<22:26, 17.95s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.37it/s]26<19:41, 15.97s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.48it/s]38<18:05, 14.87s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.67it/s]50<16:41, 13.91s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]03<16:06, 13.61s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.34it/s]18<16:33, 14.19s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]33<16:34, 14.41s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.53it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.28it/s]47<16:02, 14.15s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.54it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]04<16:47, 15.03s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.23it/s]16<15:27, 14.06s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.83it/s]30<15:13, 14.05s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]43<14:48, 13.89s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]15<20:06, 19.16s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.54it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]29<18:15, 17.68s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.85it/s]47<18:00, 17.71s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.68it/s]47<30:28, 30.47s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.30it/s]50<39:42, 40.38s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.22it/s]20<35:56, 37.18s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]34<28:42, 30.22s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.27it/s]52<24:52, 26.65s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.51it/s]26<7:35:12, 496.58s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.02it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.80it/s]39<5:16:29, 351.66s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]52<3:40:58, 250.16s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]05<2:34:57, 178.80s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]19<1:50:01, 129.43s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.05s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.07it/s]32<1:18:54, 94.69s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.16it/s]45<57:09, 70.00s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.63it/s]00<42:49, 53.53s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]16<33:09, 42.33s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 27.69it/s]30<25:55, 33.82s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]43<20:32, 27.39s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.04it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 27.83it/s]02<18:16, 24.91s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.27it/s]22<16:46, 23.40s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.03it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.59it/s]38<14:50, 21.20s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.50it/s]55<13:42, 20.07s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.03it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.25it/s]10<12:23, 18.58s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]28<11:53, 18.30s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.02it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]47<11:49, 18.68s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.59it/s]03<10:56, 17.74s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.03it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.71it/s]20<10:35, 17.65s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]33<09:30, 16.29s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.18it/s]47<08:50, 15.59s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]00<08:03, 14.66s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.24it/s]26<09:36, 18.02s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.00it/s]41<08:51, 17.16s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.39it/s]56<08:12, 16.40s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.46it/s]10<07:35, 15.72s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]22<06:54, 14.81s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.57it/s]41<07:07, 15.84s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]55<06:40, 15.40s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.99it/s]09<06:16, 15.05s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.06it/s]25<06:03, 15.16s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]4:01<1:58:39, 309.54s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.03it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.36it/s]4:18<1:21:20, 221.82s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.04it/s]4:35<56:04, 160.20s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.04it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.18it/s]4:55<39:24, 118.25s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.39it/s]5:14<28:00, 88.43s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.85it/s]5:32<20:14, 67.46s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.17it/s]7:15<2:04:05, 437.95s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.56it/s]7:29<1:22:52, 310.76s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.81it/s]7:44<55:30, 222.04s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]8:01<37:28, 160.63s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.65it/s]8:31<2:23:17, 661.35s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  2.63it/s]8:45<1:33:27, 467.31s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.92it/s]8:58<1:00:38, 330.78s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.54it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.62it/s]9:11<39:15, 235.54s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.00it/s]9:23<25:15, 168.41s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.54it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.48it/s]9:37<16:17, 122.21s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]9:51<10:27, 89.64s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.52it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.11it/s]0:05<06:41, 66.99s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.48it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]0:20<04:17, 51.53s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.21it/s]0:32<02:38, 39.68s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.35it/s]0:45<01:35, 31.70s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]0:58<00:51, 25.83s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.25it/s]1:09<00:21, 21.36s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.54it/s]

[7/21] Testing: LED 燈 50Wx1 壁投式 220V

Batches: 100%|██████████| 1/1 [00:00<00:00, 18.49it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.18s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.91it/s]7<28:54, 17.52s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.20it/s]3<27:07, 16.61s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.46it/s]0<26:55, 16.66s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.24it/s]8<27:35, 17.25s/it]
Batches: 100%|██████████| 5/5 [16:13<00:00, 194.71s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.69it/s]5<9:40:49, 366.84s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.42it/s]3<6:29:15, 248.47s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.65it/s]1<4:27:59, 172.90s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.35it/s]8<3:09:21, 123.49s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.74it/s]3<2:15:54, 89.61s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.79it/s]01<1:40:57, 67.31s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.76it/s]19<1:17:31, 52.26s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.50it/s]37<1:01:12, 41.73s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.33it/s]09<56:18, 38.83s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.57s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.30it/s]28<47:13, 32.95s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.30it/s]43<39:09, 27.64s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.09it/s]01<34:23, 24.56s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]15<29:41, 21.47s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.64it/s]34<28:21, 20.76s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.06it/s]49<25:44, 19.07s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.17s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.89it/s]06<24:30, 18.38s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.25it/s]34<4:48:38, 219.22s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  1.84s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  2.29it/s]56<3:28:06, 160.08s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.64it/s]13<2:30:33, 117.31s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.84it/s]33<1:51:21, 87.91s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.08s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]05<1:29:04, 71.26s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]40<1:14:18, 60.25s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.93it/s]00<58:36, 48.17s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]18<47:15, 39.38s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]40<1:01:44, 52.17s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.17s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.92it/s]56<47:58, 41.12s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.36it/s]12<38:34, 33.54s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.70it/s]30<32:42, 28.86s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]47<28:22, 25.42s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.61it/s]05<25:39, 23.33s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.00it/s]25<24:05, 22.23s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.99it/s]44<22:37, 21.21s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]04<21:46, 20.73s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]20<19:59, 19.35s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]36<18:51, 18.55s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.61it/s]58<19:34, 19.57s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.21it/s]16<18:35, 18.90s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.66it/s]34<18:13, 18.85s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.42it/s]51<17:11, 18.09s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.24it/s]25<21:22, 22.91s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.25it/s]43<19:33, 21.34s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.12it/s]03<18:51, 20.96s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.57it/s]37<22:06, 25.02s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]36<30:29, 35.18s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.06it/s]01<27:12, 32.01s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]18<22:58, 27.57s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]50<23:33, 28.85s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.84it/s]16<22:32, 28.17s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.04it/s]34<19:33, 24.97s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.54it/s]12<22:07, 28.87s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.17s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.68it/s]31<19:23, 25.86s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]47<16:54, 23.05s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]05<15:25, 21.52s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]25<14:46, 21.12s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.89it/s]42<13:30, 19.78s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.77it/s]53<23:29, 35.23s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]10<19:18, 29.70s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.31it/s]28<16:41, 26.34s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.39it/s]44<14:16, 23.14s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.40it/s]09<14:13, 23.70s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.65it/s]27<12:51, 22.03s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.95it/s]46<11:53, 20.98s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.15it/s]03<10:53, 19.79s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]20<10:09, 19.04s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.72it/s]37<09:26, 18.29s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.13it/s]54<08:59, 17.98s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.43it/s]10<08:22, 17.32s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.34it/s]27<08:02, 17.22s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]43<07:37, 16.93s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.73it/s]00<07:23, 17.06s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.69it/s]59<34:49, 83.59s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.80it/s]15<25:16, 63.20s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]49<20:51, 54.41s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.83it/s]03<15:35, 42.54s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.93it/s]21<12:18, 35.17s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.82it/s]47<10:46, 32.30s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.37it/s]0:14<09:44, 30.76s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.07it/s]0:33<08:09, 27.22s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.40it/s]0:49<06:45, 23.84s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.64it/s]1:06<05:50, 21.90s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.24it/s]1:26<05:16, 21.09s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.06it/s]1:44<04:42, 20.15s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.81it/s]2:02<04:15, 19.66s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]2:22<03:55, 19.66s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]2:41<03:33, 19.42s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.23s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 27.37it/s]3:02<03:19, 19.93s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.64it/s]3:17<02:46, 18.52s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.54it/s]0:21<42:41, 320.20s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.21s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.89it/s]0:39<26:47, 229.64s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.36it/s]0:59<16:39, 166.55s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]1:28<10:27, 125.43s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.59s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.16it/s]1:46<06:12, 93.01s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.23it/s]2:05<03:32, 70.81s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.48it/s]2:22<01:49, 54.88s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]2:40<00:43, 43.85s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]

[8/21] Testing: LED 燈 100Wx1 壁投式 220V

Batches: 100%|██████████| 1/1 [00:00<00:00, 18.68it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.37it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]9<6:35:37, 239.77s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 27.03it/s]7<2:58:36, 109.35s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.56it/s]5<1:49:06, 67.49s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.16it/s]2<1:16:14, 47.65s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.52it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.77it/s]9<57:35, 36.38s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]6<47:03, 30.03s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.15it/s]6<41:30, 26.78s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.05it/s]3<40:51, 26.64s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.35it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.65it/s]4<37:59, 25.05s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.66it/s]00<37:55, 25.29s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.83it/s]15<32:40, 22.03s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.82it/s]31<29:55, 20.41s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.25it/s]48<27:54, 19.25s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]07<27:16, 19.03s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.44it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]22<25:30, 18.01s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]35<22:53, 16.35s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.77it/s]52<22:55, 16.57s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.44it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.65it/s]11<23:46, 17.40s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]29<23:41, 17.55s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.32it/s]46<23:19, 17.49s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.59it/s]09<24:56, 18.94s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.94it/s]39<28:56, 22.26s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.55it/s]07<30:42, 23.93s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]28<29:11, 23.04s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.49it/s]43<26:04, 20.86s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.72it/s]01<24:37, 19.97s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.52it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]21<24:04, 19.78s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.49it/s]50<27:23, 22.83s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.46it/s]15<27:39, 23.38s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.64it/s]42<28:26, 24.38s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.62it/s]06<27:49, 24.19s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.29it/s]31<27:40, 24.41s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]59<28:40, 25.69s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.35it/s]28<29:16, 26.61s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]56<29:25, 27.17s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.36it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]18<27:05, 25.39s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.24it/s]35<24:08, 22.99s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.37it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]54<22:23, 21.66s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.37it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]20<23:34, 23.19s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.50it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.89it/s]36<21:02, 21.04s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]52<18:59, 19.32s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]09<18:07, 18.75s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]49<23:45, 25.02s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]06<21:05, 22.60s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.28it/s]34<22:11, 24.22s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.37it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.14it/s]58<21:46, 24.19s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.83it/s]16<19:52, 22.50s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.61it/s]36<18:49, 21.71s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.89it/s]55<17:35, 20.70s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.38it/s]17<17:33, 21.08s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.19it/s]33<16:08, 19.76s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.44it/s]51<15:25, 19.28s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.36it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.47it/s]10<15:00, 19.15s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.58it/s]27<14:07, 18.41s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]56<16:05, 21.46s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.22it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]37<20:09, 27.49s/it]
Batches: 100%|██████████| 5/5 [02:10<00:00, 26.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.28it/s]09<46:32, 64.95s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.89it/s]26<35:21, 50.52s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.41it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.72it/s]6:13<10:36:21, 931.27s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.05s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]6:33<7:18:39, 657.99s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]7:04<5:05:29, 470.00s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.90it/s]7:25<3:32:17, 335.20s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.43it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.46it/s]7:50<2:29:19, 242.14s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.16it/s]8:13<1:45:51, 176.44s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.98it/s]8:38<1:16:23, 130.94s/it]
Batches: 100%|██████████| 5/5 [15:04<00:00, 180.96s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.07it/s]3:56<3:28:00, 367.08s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]4:16<2:24:35, 262.90s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]7:07<13:17:35, 1495.48s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.07s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.82it/s]7:26<9:03:42, 1052.34s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.18it/s]7:52<6:12:13, 744.44s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.45it/s]8:13<4:14:56, 527.46s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]8:38<2:55:47, 376.71s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.25s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.89it/s]8:55<2:01:01, 268.96s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.83it/s]9:11<1:23:37, 192.97s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.45it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.11it/s]9:37<59:28, 142.73s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]9:59<42:43, 106.79s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.38it/s]0:20<30:58, 80.80s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.23it/s]0:39<22:51, 62.33s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.52it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.55it/s]0:54<16:48, 48.04s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.23it/s]1:12<13:04, 39.22s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.42it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]1:29<10:15, 32.41s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.37it/s]1:46<08:21, 27.85s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]2:10<07:32, 26.64s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.61it/s]3:09<09:43, 36.46s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.35it/s]3:30<07:56, 31.76s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.79it/s]3:52<06:42, 28.78s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.73it/s]4:13<05:46, 26.63s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.62it/s]4:40<05:18, 26.53s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.04it/s]5:07<04:55, 26.84s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.49it/s]5:31<04:19, 25.91s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.39it/s]5:55<03:47, 25.22s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]6:18<03:16, 24.55s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.27it/s]6:39<02:45, 23.62s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.49it/s]6:59<02:14, 22.42s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]7:24<01:57, 23.41s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.50it/s]7:48<01:34, 23.51s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.52it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.86it/s]8:12<01:11, 23.77s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.99it/s]8:34<00:45, 22.96s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.37it/s]8:55<00:22, 22.62s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.24s/it]

[9/21] Testing: LED 燈 20Wx2 吸頂式 220V

Batches: 100%|██████████| 1/1 [00:00<00:00, 18.74it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.38s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.13it/s]3<2:00:35, 73.09s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.50s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]2<1:27:13, 53.40s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.19it/s]1<1:45:07, 65.02s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.46it/s]2<1:22:26, 51.52s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.42s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.61it/s]5<1:11:13, 44.98s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.48it/s]1<1:05:45, 41.98s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.73it/s]9<57:51, 37.33s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.95it/s]3<50:51, 33.17s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.54it/s]6<54:43, 36.09s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.43it/s]05<55:34, 37.05s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.34s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]32<50:16, 33.89s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.22it/s]58<46:14, 31.53s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.67it/s]30<45:48, 31.59s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.00it/s]27<56:19, 39.30s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.29s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.57it/s]52<49:47, 35.15s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.89it/s]17<44:55, 32.09s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.06it/s]10<52:56, 38.27s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.40s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.27it/s]37<47:51, 35.01s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.25it/s]21<50:40, 37.54s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.08s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]49<46:28, 34.86s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.29s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.64it/s]21<44:39, 33.92s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.79it/s]47<41:06, 31.62s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.47it/s]05<35:19, 27.52s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.51s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.44it/s]37<36:22, 28.72s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.40it/s]59<33:29, 26.80s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.42s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.54it/s]20<30:52, 25.04s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.14it/s]52<32:57, 27.08s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.34s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.12it/s]25<34:45, 28.97s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.73it/s]51<33:09, 28.02s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.56it/s]07<28:34, 24.50s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.53s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.83it/s]31<27:40, 24.06s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.35it/s]54<27:14, 24.03s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.23s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.83it/s]23<28:17, 25.33s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.24it/s]02<32:27, 29.51s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.29s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.17it/s]02<41:47, 38.57s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.06s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.89it/s]33<38:37, 36.22s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]58<34:39, 33.01s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.76it/s]20<30:48, 29.81s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]43<28:15, 27.79s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.28it/s]10<27:18, 27.31s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.98it/s]31<25:06, 25.53s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]56<24:34, 25.43s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.54it/s]22<24:11, 25.46s/it]
Batches: 100%|██████████| 5/5 [00:09<00:00,  1.97s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.67it/s]06<29:02, 31.11s/it]
Batches: 100%|██████████| 5/5 [00:14<00:00,  2.81s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.40it/s]35<27:49, 30.35s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]59<25:48, 28.68s/it]
Batches: 100%|██████████| 5/5 [00:10<00:00,  2.07s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.09it/s]38<28:02, 31.75s/it]
Batches: 100%|██████████| 5/5 [00:13<00:00,  2.71s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.29it/s]12<28:02, 32.35s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.48s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.46it/s]32<24:24, 28.72s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.30s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.64it/s]58<23:09, 27.79s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.40it/s]25<22:25, 27.45s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.34s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.43it/s]44<20:04, 25.08s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.11it/s]08<19:26, 24.82s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.24it/s]30<18:22, 23.97s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.18it/s]48<16:35, 22.12s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.82it/s]09<16:02, 21.87s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]29<15:04, 21.03s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.42it/s]49<14:29, 20.71s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.57it/s]07<13:46, 20.15s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.94it/s]26<13:05, 19.64s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.74it/s]48<13:20, 20.53s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.38it/s]04<12:09, 19.20s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.21it/s]23<11:44, 19.03s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.17it/s]45<11:54, 19.84s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.99it/s]04<11:24, 19.57s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]21<10:42, 18.88s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.89it/s]41<10:29, 19.09s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.62it/s]04<10:53, 20.43s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.73it/s]43<13:22, 25.88s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.38it/s]04<12:16, 24.55s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.95it/s]21<10:45, 22.24s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.95it/s]41<10:06, 21.65s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.47it/s]57<08:57, 19.92s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.38s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.79it/s]20<09:03, 20.92s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.72it/s]36<08:00, 19.23s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]53<07:26, 18.61s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.61it/s]16<07:36, 19.85s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.92it/s]36<07:21, 20.09s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.84it/s]01<07:30, 21.45s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.22it/s]23<07:11, 21.56s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.60it/s]45<06:54, 21.80s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.15it/s]05<06:19, 21.08s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]39<07:08, 25.19s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.38it/s]12<07:18, 27.39s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.85it/s]38<06:47, 27.15s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.34s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.29it/s]59<05:51, 25.09s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.60it/s]21<05:13, 24.11s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]45<04:50, 24.22s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]11<04:30, 24.60s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.91it/s]44<04:31, 27.20s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]23<04:38, 30.90s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]51<03:59, 29.99s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.14it/s]06<02:58, 25.49s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.25it/s]40<02:47, 27.91s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.71it/s]03<02:12, 26.47s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.58it/s]27<01:43, 25.82s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.36it/s]57<01:21, 27.01s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.47s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.54it/s]19<00:51, 25.61s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.84it/s]22<00:36, 36.76s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]

[10/21] Testing: LED燈 40Wx1 平板燈

Batches: 100%|██████████| 1/1 [00:00<00:00, 18.16it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]6<44:29, 26.97s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.35it/s]4<44:15, 27.10s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]3<37:44, 23.35s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.66it/s]5<36:59, 23.12s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.98it/s]7<30:11, 19.07s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.83it/s]3<33:13, 21.21s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.01it/s]5<28:18, 18.26s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]5<33:46, 22.03s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.88it/s]1<35:35, 23.47s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.52it/s]37<31:21, 20.90s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.80it/s]51<27:52, 18.80s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.05s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.49it/s]05<25:29, 17.38s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.22it/s]30<28:26, 19.62s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.93it/s]00<32:49, 22.90s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.21it/s]11<27:10, 19.18s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.47it/s]25<24:59, 17.85s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.65it/s]42<24:20, 17.59s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.65it/s]08<27:21, 20.02s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.58it/s]21<24:02, 17.80s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.12it/s]36<22:35, 16.95s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.60it/s]50<21:23, 16.24s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.78it/s]09<21:59, 16.91s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.65it/s]23<20:52, 16.26s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.05it/s]45<22:45, 17.96s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.72it/s]09<24:25, 19.55s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]35<26:47, 21.73s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.51it/s]52<24:38, 20.25s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.18it/s]15<25:22, 21.15s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]30<22:32, 19.04s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.51it/s]43<20:08, 17.26s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.88it/s]53<17:29, 15.22s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.14it/s]08<17:13, 15.20s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.37it/s]35<20:48, 18.64s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.68it/s]57<21:46, 19.79s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]10<19:06, 17.64s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.71it/s]23<17:19, 16.25s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.64it/s]36<15:56, 15.18s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.15s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.62it/s]53<16:16, 15.76s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.15it/s]10<16:20, 16.08s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.05s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]29<17:03, 17.06s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.82it/s]48<17:19, 17.62s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.37it/s]01<15:34, 16.11s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.95it/s]13<14:13, 14.97s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.54it/s]26<13:30, 14.47s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.35it/s]59<18:11, 19.85s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.05s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.93it/s]20<18:19, 20.37s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.19s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.94it/s]42<18:30, 20.95s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.56it/s]07<19:09, 22.12s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]57<25:51, 30.43s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]08<20:33, 24.67s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.48it/s]24<17:55, 21.95s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.89it/s]38<15:46, 19.72s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.45it/s]00<15:56, 20.35s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.25it/s]22<15:52, 20.70s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]34<13:41, 18.27s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.58it/s]01<15:19, 20.90s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.26it/s]18<14:06, 19.70s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.81it/s]35<13:09, 18.80s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.75it/s]04<14:53, 21.79s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.42it/s]32<15:51, 23.79s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]46<13:28, 20.72s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.25it/s]03<12:23, 19.56s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.63it/s]29<13:23, 21.71s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.89it/s]49<12:39, 21.10s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.99it/s]06<11:39, 19.99s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.11it/s]33<12:31, 22.10s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.44it/s]05<13:39, 24.84s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]27<12:47, 24.00s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.02it/s]51<12:25, 24.05s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.07s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.01it/s]03<10:13, 20.46s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.62it/s]25<10:02, 20.77s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.14it/s]41<09:04, 19.46s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.60it/s]53<07:46, 17.27s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.49it/s]15<08:04, 18.65s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.31it/s]31<07:24, 17.77s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.09it/s]55<07:53, 19.72s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.93it/s]24<08:36, 22.45s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 26.92it/s]43<07:50, 21.40s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.34it/s]59<06:57, 19.88s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.01it/s]25<07:15, 21.75s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]56<07:44, 24.47s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.86it/s]19<07:10, 23.92s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]44<06:53, 24.33s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.74it/s]10<06:37, 24.81s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.44it/s]24<05:24, 21.66s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.14s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.37it/s]50<05:22, 23.03s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.05s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.18it/s]07<04:35, 21.16s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.49it/s]21<03:48, 19.02s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]58<04:26, 24.25s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.71it/s]28<04:20, 26.01s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.39it/s]58<04:05, 27.27s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.43it/s]19<03:23, 25.48s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.28it/s]36<02:39, 22.75s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.93it/s]55<02:09, 21.61s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.06it/s]12<01:41, 20.32s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]05<02:00, 30.17s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.75it/s]22<01:18, 26.09s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.00it/s]37<00:45, 22.75s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.19it/s]09<00:25, 25.53s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]

[11/21] Testing: LED燈 20Wx1 山型燈

Batches: 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]3<21:46, 13.19s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.57it/s]6<21:57, 13.44s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.14it/s]0<21:38, 13.39s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.57it/s]1<19:52, 12.42s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.48it/s]5<20:56, 13.23s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.54it/s]6<19:20, 12.35s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]0<20:02, 12.93s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.28it/s]4<20:33, 13.41s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.16it/s]9<20:43, 13.67s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.63it/s]10<19:37, 13.08s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]21<18:04, 12.18s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.27it/s]34<18:30, 12.62s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]46<18:07, 12.50s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]57<17:11, 11.99s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]14<19:07, 13.50s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.76it/s]26<18:20, 13.10s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.15it/s]40<18:20, 13.26s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]52<17:43, 12.97s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]06<17:36, 13.04s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]18<17:11, 12.90s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.08it/s]30<16:35, 12.60s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.44it/s]43<16:39, 12.81s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.69it/s]55<16:07, 12.57s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.08it/s]08<16:08, 12.75s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.31it/s]22<16:06, 12.89s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.68it/s]38<17:18, 14.04s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.28it/s]51<16:37, 13.67s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.46it/s]04<16:05, 13.41s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.62it/s]20<16:38, 14.07s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.83it/s]34<16:28, 14.13s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.32it/s]47<15:45, 13.70s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.67it/s]58<14:46, 13.03s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]09<13:57, 12.51s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.99it/s]22<13:51, 12.59s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.88it/s]35<13:34, 12.53s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.38it/s]50<14:08, 13.26s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.31it/s]02<13:44, 13.09s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]16<13:38, 13.21s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]31<14:00, 13.77s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.43it/s]44<13:28, 13.48s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]56<13:04, 13.29s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.67it/s]09<12:37, 13.06s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]24<12:51, 13.54s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.02it/s]43<14:13, 15.24s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.23it/s]57<13:44, 14.98s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.18it/s]08<12:28, 13.85s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.54it/s]23<12:19, 13.95s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.79it/s]33<11:13, 12.94s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.57it/s]49<11:44, 13.82s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.91it/s]01<10:56, 13.12s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.56it/s]14<10:44, 13.15s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]25<10:04, 12.60s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]40<10:25, 13.30s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.73it/s]54<10:19, 13.46s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.60it/s]06<09:52, 13.17s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]23<10:21, 14.13s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.50it/s]38<10:16, 14.35s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.65it/s]59<11:36, 16.58s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.32it/s]16<11:19, 16.58s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]29<10:23, 15.58s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.11it/s]43<09:47, 15.05s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.36it/s]57<09:23, 14.84s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.21it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]10<08:44, 14.16s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.15it/s]29<09:18, 15.50s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.40it/s]41<08:31, 14.60s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.66it/s]52<07:42, 13.60s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.50it/s]05<07:22, 13.40s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.13it/s]17<06:54, 12.96s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.17it/s]30<06:36, 12.79s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.08it/s]42<06:16, 12.56s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]59<06:50, 14.16s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.88it/s]13<06:29, 13.91s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]26<06:12, 13.79s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]42<06:14, 14.41s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.97it/s]55<05:51, 14.05s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.76it/s]11<05:45, 14.41s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.85it/s]25<05:32, 14.45s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.39it/s]40<05:20, 14.57s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.46it/s]53<04:58, 14.22s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.19it/s]06<04:34, 13.70s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.21it/s]19<04:15, 13.43s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.80it/s]30<03:47, 12.63s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.44it/s]42<03:33, 12.56s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.13it/s]56<03:30, 13.15s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.40it/s]12<03:28, 13.88s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.47it/s]24<03:06, 13.34s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]38<02:53, 13.36s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.41it/s]52<02:43, 13.66s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]04<02:26, 13.32s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]16<02:08, 12.84s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]29<01:56, 12.91s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.15it/s]44<01:47, 13.38s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.01it/s]55<01:28, 12.71s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]11<01:23, 13.87s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.31it/s]27<01:11, 14.24s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]38<00:53, 13.30s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]55<00:43, 14.51s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.28it/s]09<00:28, 14.32s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.71it/s]23<00:14, 14.39s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]

[12/21] Testing: LED燈 10Wx1 山型燈

Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.17it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.30it/s]0<33:02, 20.03s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]8<31:38, 19.37s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.06it/s]6<29:51, 18.47s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.65it/s]6<30:35, 19.12s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.01it/s]6<30:50, 19.48s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.36it/s]7<31:17, 19.98s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.95it/s]2<28:12, 18.20s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]3<29:41, 19.36s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]9<27:35, 18.19s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.19it/s]06<26:55, 17.95s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]29<28:42, 19.35s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]55<31:12, 21.28s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.23it/s]18<31:51, 21.97s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.32it/s]33<28:32, 19.91s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.90it/s]57<29:47, 21.02s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.39it/s]32<35:16, 25.19s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.13it/s]48<31:01, 22.42s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.43it/s]06<29:05, 21.29s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]24<27:03, 20.04s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.92it/s]52<30:12, 22.66s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.43it/s]16<30:10, 22.92s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.48it/s]02<38:42, 29.77s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]25<35:51, 27.94s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]42<31:14, 24.66s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]13<32:58, 26.38s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]35<30:58, 25.11s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.26it/s]52<27:49, 22.87s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.65it/s]16<27:33, 22.97s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.66it/s]32<24:40, 20.85s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.61it/s]46<22:12, 19.03s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]12<24:17, 21.13s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]31<22:57, 20.26s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]51<22:36, 20.24s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]06<20:29, 18.63s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]45<27:00, 24.94s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]07<25:23, 23.80s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]24<22:55, 21.83s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.62it/s]41<21:02, 20.36s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.57it/s]08<22:46, 22.40s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.06it/s]31<22:37, 22.63s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.64it/s]51<21:22, 21.73s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.66it/s]15<21:46, 22.53s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]28<18:38, 19.63s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.69it/s]43<17:09, 18.39s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.33it/s]58<15:54, 17.36s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.02it/s]18<16:16, 18.08s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.81it/s]35<15:39, 17.73s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]54<15:46, 18.20s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.94it/s]16<16:24, 19.31s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.84it/s]31<14:55, 17.92s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.15it/s]45<13:43, 16.81s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.32it/s]13<16:09, 20.20s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.21it/s]33<15:40, 20.01s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.24it/s]47<13:56, 18.19s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.59it/s]00<12:33, 16.75s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.85it/s]14<11:43, 15.99s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.48it/s]28<10:53, 15.20s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.31it/s]48<11:42, 16.73s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.74it/s]04<11:19, 16.57s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.32it/s]25<11:48, 17.72s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.68it/s]42<11:22, 17.51s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]04<12:03, 19.04s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.47it/s]37<14:15, 23.12s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.16it/s]55<12:59, 21.66s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.05it/s]11<11:34, 19.85s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.74it/s]33<11:38, 20.54s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.68it/s]56<11:39, 21.19s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.56it/s]29<13:16, 24.89s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]52<12:33, 24.31s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.26it/s]13<11:42, 23.43s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]28<10:05, 20.87s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.46it/s]45<09:13, 19.75s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]11<09:43, 21.60s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.02it/s]27<08:33, 19.73s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]47<08:19, 19.99s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]04<07:39, 19.13s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]21<07:02, 18.36s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.38it/s]38<06:31, 17.82s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.71it/s]51<05:44, 16.38s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]09<05:39, 16.96s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.54it/s]24<05:09, 16.29s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]39<04:48, 16.02s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.36it/s]01<05:03, 17.86s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]18<04:41, 17.62s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]39<04:39, 18.62s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.37it/s]57<04:17, 18.41s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.87it/s]18<04:09, 19.17s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.40it/s]32<03:31, 17.66s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.65it/s]50<03:13, 17.55s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]04<02:46, 16.66s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.30it/s]21<02:29, 16.60s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.64it/s]37<02:12, 16.57s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]59<02:08, 18.29s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]14<01:43, 17.26s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.44it/s]29<01:22, 16.54s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.67it/s]50<01:10, 17.74s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]09<00:54, 18.14s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.02it/s]52<00:51, 25.58s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.45it/s]20<00:26, 26.47s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.20it/s]

[13/21] Testing: LED燈 100Wx1 天井燈

Batches: 100%|██████████| 1/1 [00:00<00:00, 19.56it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.43it/s]4<40:05, 24.29s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.63it/s]7<29:27, 18.04s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]0<24:46, 15.33s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]5<24:24, 15.25s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.29it/s]2<25:13, 15.93s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]3<22:41, 14.48s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.28it/s]4<25:29, 16.44s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.81it/s]5<22:41, 14.80s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.00it/s]4<24:06, 15.90s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]35<21:56, 14.63s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.19it/s]47<20:29, 13.82s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]59<19:20, 13.19s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.79it/s]11<18:33, 12.80s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]24<18:36, 12.99s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.93it/s]43<20:48, 14.69s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]54<18:50, 13.46s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.45it/s]08<19:01, 13.75s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.60it/s]19<17:48, 13.03s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]38<20:02, 14.84s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.40it/s]51<18:51, 14.15s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]02<17:12, 13.07s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.85it/s]13<16:14, 12.50s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]24<15:27, 12.04s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]39<16:25, 12.97s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.82it/s]54<17:07, 13.70s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]07<16:27, 13.35s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.85it/s]24<17:32, 14.42s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.63it/s]36<16:25, 13.69s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.83it/s]47<15:14, 12.88s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]01<15:32, 13.33s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.95it/s]13<15:00, 13.06s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.10it/s]25<14:15, 12.58s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.84it/s]20<28:07, 25.18s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.37it/s]39<25:40, 23.34s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.23it/s]53<22:20, 20.62s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.28it/s]07<20:04, 18.82s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]24<18:53, 17.99s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.24it/s]45<19:44, 19.11s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.83it/s]56<16:57, 16.68s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.72it/s]09<15:21, 15.36s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]23<14:43, 14.98s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.83it/s]34<13:31, 13.99s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.78it/s]47<12:51, 13.54s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]59<12:19, 13.20s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.60it/s]12<11:59, 13.09s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.05s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.68it/s]26<11:55, 13.25s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.34it/s]40<12:00, 13.60s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]54<11:54, 13.75s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.64it/s]07<11:23, 13.40s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.62it/s]20<11:07, 13.34s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.51it/s]32<10:33, 12.93s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.25it/s]46<10:34, 13.23s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 26.02it/s]00<10:33, 13.48s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.87it/s]13<10:20, 13.48s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.17it/s]26<09:53, 13.19s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]37<09:18, 12.70s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]49<08:54, 12.42s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.40it/s]01<08:32, 12.20s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.31it/s]15<08:37, 12.62s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.57it/s]28<08:37, 12.94s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.60it/s]42<08:31, 13.12s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.69it/s]12<11:36, 18.34s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.48it/s]25<10:18, 16.72s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]59<13:10, 21.96s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.52it/s]14<11:30, 19.72s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.21it/s]27<09:58, 17.60s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.91it/s]40<09:02, 16.43s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]02<09:38, 18.09s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.75it/s]15<08:28, 16.40s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.02it/s]29<07:53, 15.78s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]43<07:24, 15.31s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.60it/s]56<06:48, 14.60s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]09<06:17, 13.99s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]21<05:47, 13.36s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.97it/s]39<06:13, 14.94s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.50it/s]51<05:35, 13.99s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.71it/s]03<05:07, 13.36s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.82it/s]15<04:43, 12.90s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.52it/s]28<04:30, 12.87s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.11it/s]38<04:04, 12.22s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.38it/s]51<03:54, 12.36s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.36it/s]06<03:54, 13.03s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.94it/s]22<03:58, 14.03s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.23it/s]33<03:30, 13.14s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.05it/s]46<03:14, 12.97s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.97it/s]58<03:00, 12.91s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.03it/s]10<02:41, 12.46s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.70it/s]26<02:43, 13.65s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.00it/s]38<02:25, 13.25s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.77it/s]51<02:09, 12.94s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.95it/s]05<02:00, 13.35s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.81it/s]17<01:42, 12.81s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.34it/s]29<01:28, 12.57s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.54it/s]41<01:15, 12.61s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.81it/s]56<01:06, 13.25s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.19it/s]13<00:57, 14.34s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]26<00:41, 13.92s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.35it/s]39<00:27, 13.82s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.54it/s]59<00:15, 15.66s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]

[14/21] Testing: LED燈 10Wx1 壁式

Batches: 100%|██████████| 1/1 [00:00<00:00, 19.29it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.01it/s]5<58:09, 35.24s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.14it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.48it/s]0<47:30, 29.09s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]2<42:28, 26.27s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.21it/s]2<50:13, 31.39s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]6<1:02:59, 39.78s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.75it/s]5<51:08, 32.65s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.23it/s]2<42:28, 27.41s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]8<36:20, 23.70s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.92it/s]7<34:04, 22.47s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.73it/s]26<31:59, 21.33s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.49it/s]47<31:29, 21.23s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.28it/s]20<36:25, 24.83s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]36<32:09, 22.18s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.18it/s]59<31:51, 22.22s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.04it/s]17<29:41, 20.96s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.66it/s]32<27:09, 19.40s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.68it/s]49<25:44, 18.61s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.77it/s]12<27:21, 20.02s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.88it/s]35<27:56, 20.70s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.21it/s]53<26:40, 20.01s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]09<24:52, 18.90s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.84it/s]29<24:59, 19.22s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.95it/s]48<24:33, 19.14s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.12it/s]07<23:55, 18.89s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.95it/s]29<24:45, 19.80s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.56it/s]55<26:56, 21.85s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]12<24:44, 20.33s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.52it/s]31<24:04, 20.07s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.79it/s]50<23:09, 19.58s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.06it/s]10<22:54, 19.63s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.68it/s]32<23:21, 20.31s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.52it/s]57<24:49, 21.91s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]15<23:06, 20.70s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]31<21:10, 19.25s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.85it/s]59<23:43, 21.90s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]22<23:41, 22.22s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.82it/s]46<23:58, 22.84s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]07<22:51, 22.12s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.68it/s]26<21:40, 21.32s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.82it/s]40<19:09, 19.17s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.11it/s]02<19:41, 20.02s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]21<19:03, 19.71s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.55it/s]45<19:48, 20.85s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.59it/s]07<19:50, 21.26s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.53it/s]25<18:32, 20.23s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]53<20:20, 22.61s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]17<20:13, 22.89s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.18it/s]32<17:56, 20.69s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.13it/s]48<16:20, 19.22s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.32it/s]04<15:12, 18.24s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]21<14:41, 17.99s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]44<15:39, 19.57s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.84it/s]15<17:52, 22.82s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]33<16:28, 21.48s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.58it/s]53<15:44, 20.99s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.59it/s]10<14:32, 19.82s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.91it/s]32<14:38, 20.42s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.56it/s]55<14:53, 21.27s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]22<15:40, 22.93s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.50it/s]43<14:56, 22.41s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.68it/s]11<15:36, 24.01s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]37<15:31, 24.52s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.15it/s]02<15:14, 24.72s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.77it/s]26<14:39, 24.43s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.15it/s]45<13:21, 22.91s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]09<13:12, 23.32s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]29<12:15, 22.28s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.41it/s]55<12:25, 23.29s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]14<11:23, 22.03s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.08it/s]44<12:09, 24.30s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.65it/s]11<12:12, 25.28s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.31it/s]42<12:33, 26.91s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.78it/s]58<10:40, 23.72s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.82it/s]22<10:20, 23.88s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]40<09:10, 22.03s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.54it/s]56<08:05, 20.22s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.92it/s]16<07:40, 20.02s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.17it/s]38<07:36, 20.74s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.64it/s]04<07:50, 22.41s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.15it/s]23<07:06, 21.34s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.12it/s]40<06:22, 20.13s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.02it/s]12<07:05, 23.63s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.47it/s]31<06:18, 22.24s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.02it/s]52<05:47, 21.74s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.88it/s]15<05:34, 22.29s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.54it/s]32<04:47, 20.55s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.24it/s]06<05:19, 24.61s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.27it/s]28<04:44, 23.71s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.64it/s]45<04:01, 21.97s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.80it/s]24<04:29, 26.97s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.67it/s]50<04:00, 26.74s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.18it/s]13<03:23, 25.41s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.74it/s]31<02:42, 23.23s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]03<02:35, 25.87s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.63it/s]23<02:00, 24.12s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.74it/s]53<01:43, 25.99s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.56it/s]28<01:25, 28.65s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.41it/s]51<00:54, 27.04s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.19it/s]25<00:28, 28.92s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]

[15/21] Testing: LED燈 10Wx1 壁式

Batches: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.96it/s]1<36:16, 21.98s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]3<35:22, 21.66s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]7<37:05, 22.94s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.93it/s]8<35:10, 21.99s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.13it/s]9<39:59, 25.26s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.75it/s]8<36:25, 23.25s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.47it/s]1<35:44, 23.06s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.55it/s]4<40:17, 26.28s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 27.18it/s]6<37:48, 24.93s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.05it/s]53<33:30, 22.34s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.17it/s]14<32:42, 22.05s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.22it/s]37<32:49, 22.38s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 26.33it/s]57<31:18, 21.59s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.17it/s]14<29:02, 20.27s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]32<27:34, 19.47s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.56it/s]50<26:36, 19.00s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]11<27:04, 19.57s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.49it/s]38<29:51, 21.84s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]03<30:44, 22.77s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]26<30:36, 22.96s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]46<29:04, 22.09s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.91it/s]14<30:58, 23.82s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.13it/s]33<28:49, 22.47s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.66it/s]51<26:30, 20.93s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.35it/s]11<25:52, 20.71s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.02it/s]28<24:14, 19.65s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]46<23:07, 19.01s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]03<22:09, 18.46s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]22<22:16, 18.83s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.06it/s]42<22:06, 18.96s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.21it/s]57<20:37, 17.94s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.79it/s]15<20:21, 17.96s/it]
Batches: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.16it/s]35<20:35, 18.44s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.23it/s]09<25:31, 23.21s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]29<23:58, 22.14s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]53<24:13, 22.72s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.70it/s]19<24:59, 23.80s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.95it/s]38<22:59, 22.26s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.80it/s]02<23:13, 22.85s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.66it/s]20<21:27, 21.47s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]38<20:01, 20.37s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]58<19:38, 20.31s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]18<19:04, 20.08s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]39<18:59, 20.35s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.58it/s]14<22:45, 24.82s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.71it/s]40<22:41, 25.21s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.56it/s]03<21:43, 24.59s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.05it/s]24<20:16, 23.39s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.87it/s]52<21:10, 24.91s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.52it/s]12<19:26, 23.33s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.85it/s]26<16:51, 20.64s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]01<19:51, 24.83s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.43it/s]23<18:42, 23.89s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.81it/s]45<18:03, 23.55s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.83it/s]04<16:36, 22.14s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]22<15:18, 20.88s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]41<14:28, 20.19s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]01<14:05, 20.13s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.84it/s]17<12:55, 18.91s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]41<13:44, 20.62s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.51it/s]29<18:34, 28.59s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.45it/s]48<16:16, 25.70s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.17it/s]05<14:23, 23.33s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]22<12:51, 21.43s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.25it/s]43<12:16, 21.04s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.66it/s]07<12:25, 21.93s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.51it/s]25<11:27, 20.82s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.84it/s]48<11:28, 21.52s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.25it/s]24<13:22, 25.87s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.45it/s]40<11:25, 22.86s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.84it/s]29<14:55, 30.89s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]57<13:56, 29.88s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.38it/s]12<11:30, 25.56s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.72it/s]28<09:46, 22.56s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.02it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.81it/s]00<10:36, 25.47s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.42it/s]18<09:13, 23.05s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.14it/s]40<08:48, 22.99s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.80it/s]58<07:47, 21.25s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.47it/s]16<07:07, 20.34s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]35<06:41, 20.05s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.42it/s]52<06:02, 19.10s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.96it/s]12<05:49, 19.43s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]35<05:49, 20.54s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]57<05:34, 20.92s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.10it/s]17<05:09, 20.61s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.48it/s]36<04:39, 19.98s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.66it/s]56<04:22, 20.16s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.33it/s]13<03:49, 19.12s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.37it/s]32<03:30, 19.10s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.05it/s]54<03:19, 19.97s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 26.58it/s]12<02:55, 19.48s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.65it/s]34<02:40, 20.03s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.95it/s]52<02:16, 19.53s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.16it/s]13<01:59, 19.89s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.23it/s]27<01:31, 18.29s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]59<01:29, 22.29s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.48it/s]23<01:08, 22.93s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.16s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]33<00:37, 18.88s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.26it/s]42<00:16, 16.02s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]

[16/21] Testing: LED燈 50Wx1 壁投式

Batches: 100%|██████████| 1/1 [00:00<00:00, 16.50it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.22s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.17it/s]9<15:49,  9.59s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.21s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.23it/s]9<15:41,  9.60s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.21s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.69it/s]8<15:20,  9.49s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.21s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.83it/s]2<37:10, 23.23s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.51it/s]7<43:13, 27.30s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.06it/s]1<46:36, 29.75s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.32it/s]4<47:32, 30.67s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.58it/s]9<48:57, 31.93s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]1<48:27, 31.95s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.23it/s]35<49:05, 32.72s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]04<46:39, 31.45s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.78it/s]33<45:01, 30.70s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]17<50:33, 34.86s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.81it/s]51<49:46, 34.73s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.84it/s]21<47:10, 33.30s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.54it/s]50<44:31, 31.80s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]37<50:27, 36.48s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]13<49:28, 36.20s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.19it/s]48<48:24, 35.86s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.89it/s]30<50:13, 37.67s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.67it/s]02<47:40, 36.21s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.98it/s]39<47:10, 36.28s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.54it/s]12<45:25, 35.40s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.29it/s]46<44:21, 35.02s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.67it/s]24<44:53, 35.91s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.38it/s]00<44:03, 35.72s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.97it/s]37<44:07, 36.27s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.33it/s]12<43:08, 35.95s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.47it/s]44<40:57, 34.61s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]14<38:45, 33.22s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]41<36:14, 31.52s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.13it/s]13<35:41, 31.49s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.06it/s]58<39:44, 35.59s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.02it/s]49<44:20, 40.32s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.56it/s]19<40:09, 37.07s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.47it/s]56<39:33, 37.09s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.53it/s]34<39:17, 37.42s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.99it/s]05<36:41, 35.50s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.93it/s]38<35:19, 34.74s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.21it/s]29<39:43, 39.72s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.02it/s]01<36:45, 37.38s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.46it/s]31<33:59, 35.17s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.63it/s]11<34:40, 36.51s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]41<32:17, 34.59s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.37it/s]11<30:31, 33.30s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.59it/s]51<31:47, 35.32s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.93it/s]24<30:23, 34.40s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]04<31:15, 36.06s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.71it/s]35<29:28, 34.67s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.20it/s]05<27:49, 33.40s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.55it/s]40<27:29, 33.67s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.94it/s]12<26:31, 33.15s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.58it/s]45<26:02, 33.25s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.90it/s]18<25:23, 33.11s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.60it/s]48<24:07, 32.16s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]17<23:00, 31.38s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]48<22:20, 31.18s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]21<22:12, 31.72s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]51<21:15, 31.11s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.58it/s]22<20:38, 30.96s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]50<19:40, 30.28s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 26.79it/s]20<19:08, 30.22s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.63it/s]00<20:26, 33.14s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.67it/s]34<20:03, 33.44s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]09<19:40, 33.72s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.83it/s]44<19:20, 34.14s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.24it/s]15<18:14, 33.16s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.75it/s]55<18:44, 35.15s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.49it/s]29<18:06, 35.05s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.72it/s]00<16:50, 33.69s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.90it/s]30<15:44, 32.58s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.71it/s]01<15:00, 32.15s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]34<14:35, 32.43s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.70it/s]04<13:40, 31.58s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.47it/s]37<13:20, 32.03s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]09<12:52, 32.19s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]37<11:51, 30.92s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.00it/s]06<11:06, 30.27s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.25it/s]37<10:37, 30.38s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.43it/s]08<10:12, 30.63s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.11it/s]35<09:21, 29.55s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.76it/s]01<08:35, 28.61s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.35it/s]30<08:07, 28.69s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.18it/s]11<08:36, 32.25s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.76it/s]49<08:32, 34.20s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]19<07:37, 32.65s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]46<06:45, 31.17s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]18<06:15, 31.29s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.81it/s]51<05:50, 31.86s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]20<05:11, 31.12s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.33it/s]01<05:06, 34.02s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.92it/s]27<04:11, 31.42s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]53<03:28, 29.79s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.32it/s]22<02:57, 29.61s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.50it/s]52<02:29, 29.89s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]15<01:51, 27.90s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.55it/s]45<01:25, 28.49s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.00it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.69it/s]16<00:58, 29.14s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.44it/s]47<00:29, 29.58s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]

[17/21] Testing: LED燈 10Wx1 嵌入式

Batches: 100%|██████████| 1/1 [00:00<00:00, 22.52it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]2<37:08, 22.51s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.20it/s]4<36:05, 22.10s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.73it/s]2<32:56, 20.38s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.30it/s]8<36:13, 22.64s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.96it/s]7<33:30, 21.16s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.41it/s]7<32:27, 20.72s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.05s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]2<29:08, 18.80s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.52it/s]9<33:02, 21.55s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.46it/s]4<29:41, 19.58s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.95it/s]19<27:13, 18.16s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.79it/s]33<25:07, 16.94s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.12s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.79it/s]52<25:26, 17.35s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.57it/s]16<28:19, 19.54s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.20it/s]34<27:22, 19.10s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.20it/s]55<27:52, 19.68s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.31it/s]12<26:22, 18.84s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]29<25:17, 18.28s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.23it/s]44<23:28, 17.18s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.32it/s]04<24:18, 18.00s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]19<22:49, 17.12s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]37<23:03, 17.51s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.25it/s]55<22:40, 17.45s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.90it/s]11<22:08, 17.25s/it]
Batches: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.63it/s]30<22:14, 17.56s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.49it/s]47<22:04, 17.65s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.03it/s]06<22:01, 17.86s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]22<21:04, 17.32s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.48it/s]42<21:53, 18.25s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.91it/s]58<20:35, 17.40s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.73it/s]13<19:41, 16.88s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.63it/s]32<19:57, 17.35s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.85it/s]56<22:04, 19.48s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.22it/s]14<21:11, 18.98s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.44it/s]30<19:49, 18.02s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.30it/s]49<19:43, 18.20s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.69it/s]07<19:33, 18.33s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]30<20:45, 19.78s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.61it/s]50<20:18, 19.65s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.83it/s]05<18:32, 18.24s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.22it/s]26<19:09, 19.16s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.97it/s]44<18:33, 18.88s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]00<17:24, 18.01s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.54it/s]18<17:03, 17.95s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.76it/s]36<16:39, 17.85s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.91it/s]56<17:11, 18.76s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.50it/s]13<16:10, 17.97s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.31it/s]29<15:25, 17.46s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.39it/s]44<14:39, 16.91s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.45it/s]00<14:01, 16.50s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.50it/s]19<14:29, 17.39s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.05s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.01it/s]40<15:00, 18.38s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.35it/s]01<15:19, 19.17s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.39it/s]19<14:48, 18.90s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]38<14:18, 18.66s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.12it/s]54<13:27, 17.94s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]10<12:44, 17.38s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.36it/s]33<13:38, 19.03s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.28it/s]53<13:31, 19.33s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]15<13:46, 20.16s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.01it/s]38<14:06, 21.15s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.95it/s]55<12:55, 19.87s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.67it/s]12<12:04, 19.07s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.22it/s]30<11:34, 18.76s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.95it/s]50<11:26, 19.08s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.18it/s]11<11:23, 19.54s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.31it/s]25<10:04, 17.77s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.27it/s]46<10:19, 18.77s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.10it/s]02<09:36, 18.02s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.47it/s]21<09:27, 18.29s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.34it/s]40<09:15, 18.52s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.78it/s]56<08:32, 17.67s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.22it/s]13<08:11, 17.56s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.74it/s]33<08:16, 18.39s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.21it/s]50<07:48, 18.01s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.85it/s]11<07:48, 18.73s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.29it/s]31<07:38, 19.10s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.73it/s]53<07:43, 20.16s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]13<07:19, 19.97s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.02it/s]31<06:50, 19.55s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.92it/s]45<05:54, 17.71s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]58<05:12, 16.45s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]15<04:58, 16.60s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]35<04:59, 17.59s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.74it/s]53<04:43, 17.69s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]10<04:22, 17.52s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.50it/s]27<04:00, 17.17s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.40it/s]44<03:44, 17.31s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.11it/s]02<03:29, 17.49s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.13it/s]30<03:45, 20.51s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.32it/s]45<03:10, 19.04s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.10s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]02<02:44, 18.26s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.62it/s]20<02:26, 18.37s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]44<02:19, 19.99s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]00<01:52, 18.75s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.56it/s]16<01:29, 17.86s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]32<01:09, 17.43s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]48<00:51, 17.07s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.66it/s]03<00:32, 16.19s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.09s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]19<00:16, 16.16s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.11s/it]

[18/21] Testing: LED燈 10Wx1 吸頂式

Batches: 100%|██████████| 1/1 [00:00<00:00, 14.34it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.91it/s]4<40:11, 24.36s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.47s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.25it/s]4<36:09, 22.14s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.37s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]3<40:27, 25.03s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]6<32:46, 20.48s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.77it/s]3<35:47, 22.61s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.05it/s]1<33:09, 21.17s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.67it/s]4<33:50, 21.83s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]7<34:05, 22.23s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.64it/s]8<32:59, 21.75s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.37it/s]40<32:50, 21.89s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.70it/s]55<28:57, 19.53s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.34s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]11<27:25, 18.70s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.34s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]28<26:18, 18.14s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.16it/s]45<25:33, 17.83s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 27.34it/s]10<28:00, 19.77s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.68it/s]26<26:20, 18.81s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.10it/s]42<24:45, 17.90s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.11it/s]03<25:53, 18.95s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.58it/s]21<24:52, 18.43s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.92it/s]39<24:41, 18.52s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.26it/s]03<26:15, 19.94s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.61it/s]20<25:07, 19.33s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.47it/s]41<25:26, 19.83s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.37s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]04<25:59, 20.52s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.38s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]22<24:47, 19.83s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.37s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.39it/s]40<23:43, 19.23s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.42s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  3.53it/s]55<22:07, 18.19s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.38s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]15<22:16, 18.56s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.40it/s]40<24:13, 20.47s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.69it/s]58<23:07, 19.82s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.38s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]24<24:49, 21.59s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.37s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]40<22:35, 19.93s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.40s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.40it/s]55<20:41, 18.53s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.37s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]13<20:10, 18.35s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.29it/s]36<21:30, 19.85s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.85it/s]02<23:05, 21.65s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]17<20:29, 19.52s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.02it/s]34<19:35, 18.96s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.45it/s]55<19:51, 19.52s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.36it/s]15<19:38, 19.64s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.10it/s]11<30:06, 30.61s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.87it/s]33<27:00, 27.94s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.69it/s]58<25:45, 27.12s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]23<24:35, 26.35s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.45it/s]37<20:51, 22.75s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]51<18:10, 20.19s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.40it/s]14<18:22, 20.80s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.50it/s]32<17:26, 20.13s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.40s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]53<17:12, 20.25s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.92it/s]11<16:18, 19.57s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.33it/s]30<16:01, 19.62s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.59it/s]56<17:04, 21.35s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.68it/s]15<16:10, 20.66s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.27it/s]31<14:47, 19.28s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.52it/s]52<14:48, 19.75s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.43it/s]14<15:04, 20.57s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.06it/s]28<13:16, 18.51s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.59it/s]50<13:39, 19.50s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.38s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.56it/s]15<14:35, 21.36s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.34it/s]30<12:49, 19.23s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.61it/s]55<13:44, 21.13s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.92it/s]10<12:14, 19.32s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.65it/s]25<11:00, 17.85s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.03it/s]39<09:59, 16.64s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.38s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.07it/s]00<10:27, 17.94s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.76it/s]15<09:39, 17.05s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.45it/s]33<09:40, 17.59s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.56it/s]55<09:59, 18.73s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]23<11:08, 21.57s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.04it/s]43<10:37, 21.23s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.37s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.41it/s]04<10:13, 21.16s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]27<10:05, 21.61s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.37s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.83it/s]55<10:37, 23.61s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]10<09:06, 21.03s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]33<09:00, 21.62s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.18it/s]56<08:46, 21.95s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]14<07:58, 20.78s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.37s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.21it/s]37<07:50, 21.41s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]03<07:59, 22.85s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.99it/s]22<07:10, 21.52s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.47s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.18it/s]46<07:02, 22.26s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]59<05:52, 19.57s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.79it/s]20<05:38, 19.94s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.78it/s]36<04:58, 18.69s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]58<04:57, 19.81s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.48it/s]21<04:50, 20.77s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]42<04:32, 20.92s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.44it/s]03<04:09, 20.81s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.98it/s]23<03:45, 20.52s/it]
Batches: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.56it/s]43<03:25, 20.51s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]58<02:49, 18.81s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.02it/s]23<02:44, 20.57s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]37<02:11, 18.76s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.23it/s]57<01:53, 19.00s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.31it/s]21<01:42, 20.55s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.29s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.81it/s]32<01:11, 17.79s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.06it/s]43<00:47, 15.76s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.91it/s]54<00:28, 14.23s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.36it/s]05<00:13, 13.20s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.27s/it]

[19/21] Testing: LED燈 9Wx1 照樹燈

Batches: 100%|██████████| 1/1 [00:00<00:00, 17.29it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.88it/s]1<18:50, 11.42s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.92it/s]2<18:26, 11.29s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.41it/s]3<18:07, 11.21s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.07it/s]4<17:49, 11.14s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.75it/s]5<17:38, 11.14s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.90it/s]7<17:31, 11.18s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.26it/s]8<17:21, 11.20s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.66it/s]9<17:08, 11.18s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.12it/s]0<16:54, 11.15s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.97it/s]51<16:47, 11.19s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.07it/s]03<16:40, 11.24s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.82it/s]14<16:26, 11.21s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.59it/s]25<16:11, 11.17s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]36<15:58, 11.14s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.13it/s]47<15:45, 11.13s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.26it/s]58<15:32, 11.11s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.34s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]09<15:23, 11.13s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.72it/s]21<15:12, 11.13s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.53it/s]32<14:59, 11.11s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.59it/s]43<14:48, 11.11s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.69it/s]54<14:36, 11.10s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.62it/s]05<14:24, 11.09s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.81it/s]16<14:14, 11.10s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.76it/s]27<14:03, 11.10s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.42it/s]38<13:56, 11.15s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.43it/s]50<13:48, 11.19s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.68it/s]01<13:33, 11.15s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.28it/s]12<13:21, 11.13s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.74it/s]23<13:11, 11.15s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]34<12:59, 11.13s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.38s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  3.59it/s]45<12:53, 11.20s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.34s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]57<12:47, 11.28s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.88it/s]08<12:33, 11.25s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.32it/s]19<12:16, 11.17s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.68it/s]30<12:03, 11.13s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.56it/s]41<11:52, 11.14s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.35it/s]52<11:40, 11.12s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.39it/s]04<11:31, 11.15s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.91it/s]15<11:17, 11.11s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.80it/s]25<11:02, 11.05s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]37<10:55, 11.11s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.88it/s]48<10:41, 11.05s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.32it/s]58<10:24, 10.96s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.53it/s]10<10:19, 11.07s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.56it/s]21<10:06, 11.03s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]32<09:57, 11.07s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.34s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]43<09:49, 11.12s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.96it/s]54<09:38, 11.12s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.60it/s]05<09:27, 11.13s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.03it/s]17<09:17, 11.15s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.38it/s]28<09:06, 11.15s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.83it/s]39<08:56, 11.17s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]50<08:47, 11.21s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.41it/s]01<08:33, 11.15s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.56it/s]12<08:20, 11.11s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.36it/s]23<08:09, 11.13s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.34s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.47it/s]35<08:01, 11.21s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]46<07:51, 11.23s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.93it/s]57<07:38, 11.19s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.63it/s]08<07:26, 11.16s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.52it/s]19<07:14, 11.13s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.21it/s]31<07:06, 11.22s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.12it/s]42<06:56, 11.26s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.34s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]53<06:44, 11.24s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.80it/s]05<06:33, 11.23s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.83it/s]16<06:20, 11.19s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.10it/s]27<06:06, 11.12s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.10it/s]38<05:56, 11.15s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.49it/s]49<05:44, 11.10s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.29it/s]00<05:36, 11.23s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.55it/s]11<05:25, 11.21s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.98it/s]23<05:13, 11.20s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]34<05:05, 11.32s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.38it/s]46<04:54, 11.34s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.20it/s]57<04:42, 11.30s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.69it/s]08<04:30, 11.28s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.61it/s]20<04:23, 11.44s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.26it/s]31<04:10, 11.38s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.76it/s]42<03:56, 11.28s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.73it/s]53<03:45, 11.28s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.60it/s]04<03:33, 11.21s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.76it/s]16<03:20, 11.16s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.01it/s]26<03:08, 11.08s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.28it/s]37<02:56, 11.05s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.96it/s]48<02:45, 11.03s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.96it/s]59<02:34, 11.00s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]10<02:23, 11.05s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.75it/s]21<02:12, 11.02s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.04it/s]32<02:01, 11.01s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.55it/s]44<01:50, 11.07s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.51it/s]55<01:39, 11.04s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.73it/s]06<01:28, 11.05s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.39it/s]17<01:17, 11.05s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.28it/s]28<01:06, 11.15s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]39<00:55, 11.19s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.71it/s]51<00:44, 11.18s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.31s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.26it/s]02<00:33, 11.13s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.33s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.47it/s]13<00:22, 11.15s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]24<00:11, 11.14s/it]
Batches: 100%|██████████| 5/5 [00:06<00:00,  1.32s/it]

[20/21] Testing: LED燈 10Wx1 草皮燈

Batches: 100%|██████████| 1/1 [00:00<00:00, 15.65it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.06s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.75it/s]0<17:03, 10.34s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]0<16:46, 10.27s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.42it/s]0<16:30, 10.21s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.81it/s]0<16:15, 10.16s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.40it/s]0<15:57, 10.08s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.61it/s]0<15:50, 10.11s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.58it/s]0<15:33, 10.04s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.99it/s]0<15:22, 10.03s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.86it/s]1<15:20, 10.11s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.48it/s]41<15:08, 10.09s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.04s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.82it/s]51<15:02, 10.14s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.49it/s]01<14:52, 10.14s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.42it/s]11<14:40, 10.12s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.88it/s]21<14:28, 10.10s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.74it/s]31<14:12, 10.03s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.53it/s]41<14:01, 10.02s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.07it/s]51<13:48,  9.98s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.34it/s]01<13:35,  9.95s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.76it/s]11<13:27,  9.97s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.89it/s]21<13:26, 10.09s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.89it/s]31<13:14, 10.06s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.63it/s]41<13:03, 10.04s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.91it/s]51<12:54, 10.06s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.58it/s]01<12:43, 10.05s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.32it/s]11<12:32, 10.04s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.44it/s]21<12:17,  9.97s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]31<12:10, 10.00s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]41<12:02, 10.04s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.15it/s]51<11:54, 10.06s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.28it/s]01<11:42, 10.03s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.58it/s]11<11:26,  9.95s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.02it/s]21<11:22, 10.03s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.96it/s]31<11:13, 10.06s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.66it/s]41<11:02, 10.04s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.43it/s]52<10:54, 10.06s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.97it/s]02<10:45, 10.09s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.71it/s]12<10:35, 10.09s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.30it/s]22<10:27, 10.12s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.85it/s]32<10:12, 10.05s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.57it/s]42<10:06, 10.11s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.27it/s]52<09:52, 10.04s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.80it/s]02<09:43, 10.06s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.66it/s]12<09:33, 10.06s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.54it/s]22<09:22, 10.04s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.33it/s]32<09:10, 10.01s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.98it/s]42<08:59,  9.99s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.55it/s]52<08:49,  9.99s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.08it/s]02<08:37,  9.95s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.89it/s]12<08:26,  9.94s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.87it/s]22<08:20, 10.01s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.34it/s]32<08:10, 10.01s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.69it/s]42<08:01, 10.04s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.49it/s]52<07:49,  9.99s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.36it/s]02<07:40, 10.01s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.72it/s]12<07:32, 10.06s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.21it/s]23<07:25, 10.11s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.66it/s]32<07:13, 10.08s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.74it/s]43<07:05, 10.14s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.30it/s]53<06:54, 10.11s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.24it/s]03<06:45, 10.14s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.63it/s]13<06:34, 10.12s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.68it/s]23<06:25, 10.15s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.66it/s]34<06:16, 10.16s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.06it/s]44<06:04, 10.14s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.26it/s]53<05:51, 10.03s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.54it/s]03<05:40, 10.01s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.78it/s]13<05:31, 10.06s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.20it/s]23<05:20, 10.02s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.50it/s]34<05:11, 10.06s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.67it/s]44<05:02, 10.07s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.29it/s]54<04:52, 10.07s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.49it/s]04<04:43, 10.12s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.49it/s]14<04:31, 10.05s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.06s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.80it/s]24<04:23, 10.14s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.39it/s]34<04:13, 10.13s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.48it/s]44<04:02, 10.11s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.02s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.15it/s]54<03:51, 10.06s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.56it/s]04<03:40, 10.02s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 20.60it/s]14<03:30, 10.01s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.79it/s]24<03:20, 10.04s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.53it/s]34<03:11, 10.07s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.19it/s]45<03:01, 10.08s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.24it/s]55<02:51, 10.11s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.19it/s]05<02:41, 10.11s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.96it/s]15<02:30, 10.02s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]25<02:20, 10.03s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.00it/s]35<02:09,  9.97s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.89it/s]45<01:59,  9.97s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.08it/s]55<01:50, 10.02s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.03it/s]05<01:39,  9.99s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.12it/s]15<01:30, 10.07s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.73it/s]25<01:21, 10.15s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.14it/s]35<01:10, 10.02s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.38it/s]45<01:00, 10.09s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.21it/s]55<00:50, 10.04s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.47it/s]05<00:40, 10.05s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.39it/s]15<00:30, 10.10s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.85it/s]25<00:20, 10.02s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.54it/s]35<00:10, 10.07s/it]
Batches: 100%|██████████| 5/5 [00:05<00:00,  1.01s/it]

[21/21] Testing: LED燈 25Wx1 高燈

Batches: 100%|██████████| 1/1 [00:00<00:00, 17.26it/s]0<?, ?it/s]
Batches: 100%|██████████| 5/5 [00:13<00:00,  2.69s/it]
Batches: 100%|██████████| 1/1 [00:01<00:00,  1.07s/it]0<33:46, 20.47s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.49s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  3.22it/s]0<33:24, 20.46s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  2.18it/s]0<32:20, 20.00s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]9<31:34, 19.74s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  2.33it/s]8<30:53, 19.51s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]8<30:40, 19.58s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.47s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]7<30:10, 19.47s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.43s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  3.47it/s]7<29:45, 19.40s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]6<29:33, 19.48s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.43s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.27it/s]15<29:06, 19.41s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.57s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]35<28:58, 19.53s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.23it/s]54<28:21, 19.34s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]13<27:51, 19.21s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]32<27:26, 19.15s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.38s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.95it/s]51<26:56, 19.02s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.13it/s]10<26:38, 19.03s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.43s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.01it/s]29<26:18, 19.02s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.43s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]48<26:06, 19.10s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.19it/s]07<25:41, 19.03s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]26<25:28, 19.10s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]45<25:06, 19.07s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.55it/s]04<24:46, 19.06s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.70it/s]23<24:22, 18.99s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]42<24:09, 19.08s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.43s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]02<23:51, 19.09s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]21<23:35, 19.13s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.59s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.29it/s]41<23:42, 19.49s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.40s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.15it/s]00<23:10, 19.31s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.03it/s]19<22:37, 19.12s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.04it/s]37<22:11, 19.02s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.38s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.07it/s]56<21:49, 18.98s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.53s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]16<21:45, 19.19s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.43s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]35<21:24, 19.17s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.15it/s]54<21:04, 19.16s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.48s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.04it/s]14<20:52, 19.27s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.70it/s]33<20:32, 19.26s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.47s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]52<20:16, 19.31s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.21it/s]11<19:47, 19.15s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]31<19:32, 19.22s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.20it/s]50<19:12, 19.21s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.28it/s]09<18:57, 19.28s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.99it/s]28<18:28, 19.10s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.00it/s]47<18:10, 19.14s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.22it/s]06<17:45, 19.03s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.78it/s]25<17:33, 19.16s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.86it/s]44<17:09, 19.06s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  3.78it/s]03<16:52, 19.10s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.64it/s]23<16:37, 19.18s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]42<16:17, 19.17s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]01<16:01, 19.23s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.43s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]20<15:38, 19.16s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.40s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.21it/s]39<15:16, 19.10s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.73it/s]58<14:55, 19.04s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]17<14:31, 18.95s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]36<14:15, 19.01s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]55<13:55, 19.00s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.43s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]14<13:36, 19.00s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]33<13:14, 18.91s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.99it/s]52<12:56, 18.95s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]11<12:38, 18.95s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]30<12:18, 18.93s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.42s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.35it/s]49<12:02, 19.00s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.55it/s]08<11:46, 19.09s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.42s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]27<11:24, 19.01s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.43s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.68it/s]46<11:04, 18.99s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.40s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.48it/s]05<10:46, 19.01s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.42s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  3.57it/s]24<10:27, 19.03s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.42s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  3.69it/s]43<10:10, 19.07s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.69it/s]02<09:52, 19.10s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.65it/s]21<09:32, 19.09s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.39s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]40<09:11, 19.03s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.42s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]59<08:52, 19.00s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.48it/s]18<08:34, 19.05s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]38<08:17, 19.15s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]57<07:58, 19.12s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.72it/s]16<07:37, 19.07s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.42s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  3.97it/s]35<07:21, 19.20s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.90it/s]54<07:01, 19.18s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.43s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.04it/s]14<06:42, 19.17s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.40s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.33it/s]33<06:23, 19.17s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.27it/s]51<06:01, 19.00s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]10<05:42, 19.05s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]30<05:24, 19.06s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]49<05:06, 19.16s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.40s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 14.86it/s]08<04:46, 19.08s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.43s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  9.91it/s]27<04:27, 19.13s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.46s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]47<04:10, 19.26s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.47s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  3.16it/s]06<03:51, 19.26s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.44s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]25<03:32, 19.31s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.03it/s]44<03:12, 19.24s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.40s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.43it/s]04<02:53, 19.27s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.50it/s]23<02:34, 19.28s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.58it/s]42<02:14, 19.19s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.45s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.18it/s]01<01:55, 19.22s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.48s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  2.03it/s]21<01:36, 19.33s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.47s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  2.88it/s]40<01:17, 19.36s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.43s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00, 12.78it/s]00<00:57, 19.30s/it]
Batches: 100%|██████████| 5/5 [00:11<00:00,  2.40s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]19<00:38, 19.28s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.43s/it]
Batches: 100%|██████████| 1/1 [00:00<00:00,  3.39it/s]38<00:19, 19.27s/it]
Batches: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]

================================================================================
📊 FINAL REPORT (Summary by Row)
================================================================================
    row_id                request  consistency_score_pct accuracy_pass  unique_variations
0        1    LED燈 35Wx1 嵌入式 220V                    3.0        ❌ FAIL                 96
1        2    LED燈 20Wx1 吊管式 220V                    2.0        ❌ FAIL                 99
2        3    LED燈 20Wx1 吸頂式 220V                    2.0        ❌ FAIL                 98
3        4     LED燈 20Wx1 壁式 220V                   10.0        ❌ FAIL                 85
4        5    LED燈 15Wx1 嵌入式 220V                    6.0        ❌ FAIL                 82
5        6    LED 燈 13Wx2 壁式 220V                    5.0        ❌ FAIL                 79
6        7   LED 燈 50Wx1 壁投式 220V                    2.0        ❌ FAIL                 97
7        8  LED 燈 100Wx1 壁投式 220V                    3.0        ❌ FAIL                 97
8        9   LED 燈 20Wx2 吸頂式 220V                    2.0        ❌ FAIL                 96
9       10         LED燈 40Wx1 平板燈                    9.0        ✅ PASS                 77
10      11         LED燈 20Wx1 山型燈                    4.0        ❌ FAIL                 85
11      12         LED燈 10Wx1 山型燈                    3.0        ❌ FAIL                 85
12      13        LED燈 100Wx1 天井燈                    3.0        ❌ FAIL                 90
13      14          LED燈 10Wx1 壁式                    2.0        ❌ FAIL                 98
14      15          LED燈 10Wx1 壁式                    4.0        ❌ FAIL                 94
15      16         LED燈 50Wx1 壁投式                    4.0        ❌ FAIL                 87
16      17         LED燈 10Wx1 嵌入式                    4.0        ❌ FAIL                 87
17      18         LED燈 10Wx1 吸頂式                    5.0        ❌ FAIL                 92
18      19          LED燈 9Wx1 照樹燈                  100.0        ❌ FAIL                  1
19      20         LED燈 10Wx1 草皮燈                  100.0        ❌ FAIL                  1
20      21          LED燈 25Wx1 高燈                  100.0        ❌ FAIL                  1

📝 Detailed report saved to: full_consistency_report.csv